create TABLE a18 (
    频道编号 varchar(10) not null,
    媒体类型 char not null,
    广告名称 varchar(256) not null,
    频道名称 varchar(256) not null,
    版本 varchar(256),
    日期 datetime not null,
    开始时间 varchar(10),
    结束时间 varchar(10),
    秒长 varchar(50) not null,
    经营企业 varchar(256),
    公众人物 varchar(256),
    是否涉性 char,
    proid int,
    附加分类 varchar(256),
    SampleID int,
    SampleType char,
    headid int,
    栏目 varchar(256) not null,
    AREANO varchar(7),
    地域名称 varchar(100),
    省 varchar(30),
    市 varchar(50),
    县 varchar(50)
)create TABLE dcc00 (
    Channelno varchar(10),
    MediaType char,
    PlayDate datetime
)create TABLE DCCUserADid (
    adid int
)create TABLE DCCUserSampleid (
    sampleid int
)create TABLE dtproperties (
    id int not null,
    objectid int,
    property varchar(64) not null,
    "value" varchar(255),
    uvalue nvarchar(255),
    lvalue image,
    version int not null,
    PRIMARY KEY (id, property)
);
CREATE UNIQUE INDEX pk_dtproperties ON dtproperties (id, property)create TABLE fufeichannel (
    channelno nvarchar(255),
    channelname nvarchar(255)
)create TABLE hefa (
    LId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime2 not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    InsertTime datetime2,
    proid int,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20),
    X1 int,
    Y1 int,
    X2 int,
    Y2 int,
    ratio float,
    acreage float,
    stationname varchar(200)
);
CREATE INDEX IX_hefa ON hefa (PlayDate, MediaType, AdId)create TABLE sysdiagrams (
    name sysname not null,
    principal_id int not null,
    diagram_id int not null,
    version int,
    definition varbinary,
    PRIMARY KEY (diagram_id)
);
CREATE UNIQUE INDEX PK__sysdiagr__C2B05B612962DF74 ON sysdiagrams (diagram_id);
CREATE UNIQUE INDEX UK_principal_name ON sysdiagrams (principal_id, name)create TABLE T_ADDataSet (
    LId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    InsertTime datetime,
    proid int,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20),
    X1 int,
    Y1 int,
    X2 int,
    Y2 int,
    ratio float,
    acreage float,
    stationname varchar(200)
);
CREATE INDEX T_ADDataSet_PK_1 ON T_ADDataSet (MediaType, Channelno, PlayDate);
CREATE INDEX IX_T_ADDataSet ON T_ADDataSet (headId, PlayDate, Channelno, MediaType)create TABLE T_ADDataSet_bh (
    LId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    InsertTime datetime,
    proid int,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20)
)create TABLE T_ADDescribe (
    ADDesid int not null,
    ADDescribe varchar(50) not null,
    userid varchar(50),
    InsertTime datetime not null
)create TABLE T_ADDescribeRelation (
    Lid int not null,
    ADid int not null,
    ADDesid varchar(50) not null,
    InsertTime datetime not null
);
CREATE UNIQUE INDEX pk1 ON T_ADDescribeRelation (Lid);
CREATE INDEX pk2 ON T_ADDescribeRelation (ADid)create TABLE T_AdInfo (
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    Enterprise varchar(256),
    MediaType varchar(50),
    remark varchar(600),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    inserttime datetime,
    IsStop char,
    EnterpriseId varchar(256),
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    CheckADApprovalNo varchar(256),
    AdTypeid int,
    Creatman varchar(20),
    ischeck char,
    QAtime datetime,
    QAmanager varchar(20),
    ProId int,
    Phone400Area varchar(100),
    PRIMARY KEY (AdId)
);
CREATE UNIQUE INDEX PK_T_AdInfo ON T_AdInfo (AdId);
CREATE INDEX Adname-Mediatype ON T_AdInfo (ADName, MediaType);
CREATE INDEX Adinfo_Version_Index ON T_AdInfo (Version);
CREATE INDEX Adname-Mediatype2 ON T_AdInfo (ADName, IsStop, MediaType, Version);
CREATE INDEX pk_adproid ON T_AdInfo (AdId, ProId);
CREATE INDEX IX_T_AdInfo ON T_AdInfo (MediaType, IsStop);
CREATE INDEX IX_T_ADInfo_ID_Name ON T_AdInfo (AdId, ADName, IsStop)create TABLE T_AdType (
    adid int,
    typeid varchar(50),
    themeid int,
    IllegalNature char,
    IsChecked char,
    Userid varchar(50),
    CheckedTime datetime,
    inserttime datetime,
    QAmanager varchar(20)
);
CREATE INDEX adtype_index_1 ON T_AdType (adid, typeid, themeid);
CREATE INDEX adid ON T_AdType (adid)create TABLE T_AllResult (
    ReportId int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId varchar(5),
    MediaType char,
    TypeName varchar(50),
    PlayDate datetime,
    IllegalItem varchar(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    InsertTime datetime,
    ImagePath varchar(256),
    AnnouncementID varchar(10),
    HandleCaseid varchar(50),
    CaseClosed varchar(50),
    headId int,
    plid int,
    cltime datetime,
    OutlawLevel varchar(50),
    Version varchar(256),
    ChannelType varchar(50),
    remark char(10),
    report_id_new int,
    ReportId_nei int,
    url1 varchar(256),
    areaname varchar(256),
    areano varchar(20),
    sheng varchar(100),
    shi varchar(100),
    xian varchar(100),
    adcount int,
    arealevel varchar(20),
    stationname varchar(200),
    acreage float,
    ChannelTypeS varchar(50),
    isws char
);
CREATE INDEX PK1 ON T_AllResult (Channelno, MediaType, PlayDate)create TABLE T_AllUploadRecord (
    id int not null,
    headid int,
    feaname varchar(100),
    mediatype char not null,
    playdate datetime not null,
    channelno varchar(10) not null,
    inserttime datetime not null,
    upMonth varchar(7),
    isgsj char not null,
    isyjj char not null,
    isgs char not null,
    ishuludao char not null,
    isswb char not null,
    isupload char not null,
    begintime varchar(50),
    isRelease varchar(1) not null
)create TABLE T_AllUploadRecord_bh (
    id int not null,
    headid int,
    feaname varchar(100),
    mediatype char not null,
    playdate datetime not null,
    channelno varchar(10) not null,
    inserttime datetime not null,
    upMonth varchar(7),
    isgsj char not null,
    isyjj char not null,
    isgs char not null,
    ishuludao char not null,
    isswb char not null,
    isupload char not null,
    begintime varchar(50),
    isRelease varchar(1) not null
)create TABLE T_Appversion (
    ID int not null,
    ApplicationVersion varchar(50) not null,
    ApplicationName varchar(50) not null,
    "Describe" varchar(200) not null,
    Inserttime date not null,
    CreateMan varchar(20) not null
)create TABLE T_AreaConduct (
    RId int not null,
    UseType varchar(6) not null,
    ConductId varchar(50) not null
)create TABLE T_AreaToList (
    id int not null,
    areano varchar(10),
    listname varchar(100),
    listid varchar(10),
    textname varchar(100),
    listtype char
)create TABLE T_AutoDecodeFile (
    id int not null,
    filename varchar(200),
    filepath varchar(800),
    channelno varchar(9),
    mediaTpye varchar(1),
    ip varchar(50),
    version varchar(50),
    inserttime datetime,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_AutoDecodeFile ON T_AutoDecodeFile (id)create TABLE T_AutoPlayList (
    ListID int not null,
    StartPos varchar(50),
    EndPos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    ZeroCrossMath varchar(50),
    EnergeMatch varchar(50),
    PlayDate varchar(10),
    HeadId int,
    AdId int,
    SampleID int,
    IsHand char,
    iscut char,
    IsCheck char,
    inserttime datetime,
    isupload char
);
CREATE INDEX IX_T_AutoPlayList ON T_AutoPlayList (HeadId)create TABLE T_AutoRunControl (
    Id int not null,
    ChannelNo varchar(50),
    MediaType char,
    WorkStationNo varchar(6),
    PNum varchar(2),
    BeginTime datetime,
    EndTime datetime,
    Creater varchar(50),
    CreateTime datetime,
    IsCopy char
)create TABLE T_AutoUpdate (
    ID int not null,
    Softwarename varchar(50),
    Version varchar(50),
    ServerIP varchar(50),
    UserName varchar(50),
    Password varchar(50),
    PortNo varchar(50),
    FilePath varchar(512),
    Inserttime datetime
)create TABLE T_AutoUpdateLog (
    ID int not null,
    SoftWareName varchar(50),
    ServerIP varchar(50),
    Version varchar(50),
    ISSERVER char,
    Inserttime datetime
)create TABLE T_BHPlayListHead (
    BHID int not null,
    HeadId int,
    Feaname varchar(100),
    RightFileName varchar(100),
    BeginTime varchar(50),
    playdate datetime,
    MediaType char,
    ChannelNo varchar(10),
    MonitorPerson varchar(50),
    IsSubmit char,
    SubmitTime datetime,
    IsGSTask char,
    IsYJTask char,
    IsCut char,
    Cuttime datetime,
    IsCheck char,
    CheckTime datetime,
    CheckPerson varchar(50),
    isUpload char,
    UploadTime datetime,
    createman varchar(50),
    createtime datetime,
    state varchar(100)
)create TABLE T_CantonChannel (
    AreNo varchar(6) not null,
    ChannelNm varchar(10) not null,
    InsertTime datetime not null,
    CreateTime datetime not null
)create TABLE T_CITY (
    PROVINCENO varchar(50),
    CITYNO varchar(50),
    CITYNAME varchar(500),
    AREALEVEL varchar(50)
)create TABLE T_Conduct (
    ConductId int not null,
    ConductInfo varchar(200) not null
)create TABLE T_ConductResult (
    id int not null,
    EnterpriseId varchar(50),
    ConductId varchar(50),
    is_stop char,
    username varchar(50),
    usertype varchar(50),
    inserttime datetime
)create TABLE T_CopyFailInfo (
    id int not null,
    sourceFile varchar(1000),
    ObjectFile varchar(1000),
    insertTime datetime,
    IsFMove char,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_CopyFailInfo ON T_CopyFailInfo (id)create TABLE T_CopyPaperFailInfo (
    id int not null,
    sourceFile varchar(5000),
    ObjectFile varchar(5000),
    insertTime datetime,
    IsFMove char,
    picid varchar(50),
    mediatype char
)create TABLE T_CopyPath (
    id int not null,
    FTPDXPATH varchar(256),
    STREAMPATH varchar(256),
    DISKNO varchar(10),
    FTPHEANID varchar(50)
)create TABLE T_COUNTRY (
    CITYNO varchar(50),
    COUNTRYNO varchar(50),
    COUNTRYNAME varchar(500),
    AREALEVEL varchar(50)
)create TABLE T_CutDateInfo (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    ISGS char,
    PRIMARY KEY (FileId)
);
CREATE UNIQUE INDEX PK_T_CutDateInfo ON T_CutDateInfo (FileId);
CREATE INDEX PK_T2_CutDateInfo ON T_CutDateInfo (Channelno, CutDate);
CREATE INDEX CUTFILE ON T_CutDateInfo (Channelno, CutDate, IsHand)create TABLE t_cutdateinfo9 (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    ISGS char
)create TABLE T_CutDateInfoAll (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    PRIMARY KEY (FileId)
);
CREATE UNIQUE INDEX PK_T_CutDateInfoAll ON T_CutDateInfoAll (FileId)create TABLE t_cutdateinfoCGGS (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    ISGS char
)create TABLE t_cutdateinfoGSOneDay (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    ISGS char
)create TABLE T_CutDateInfoYJ (
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    CheckTime datetime,
    IsChecked char,
    BDatetime varchar(20),
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    inserttime datetime,
    SampleLen varchar(50),
    SamBPos varchar(50),
    ISGS char,
    PRIMARY KEY (FileId)
);
CREATE UNIQUE INDEX PK_T_CutDateInfoYJ ON T_CutDateInfoYJ (FileId)create TABLE T_CutFailedInfo (
    HeadID varchar(20),
    Feaname varchar(200),
    FilePath varchar(500),
    DiskNo varchar(10),
    FailureType char,
    Inserttime datetime
)create TABLE T_DataTemplate (
    ID int not null,
    ThemeID int,
    DisplayName varchar(5000),
    ListName varchar(5000),
    Inserttime datetime
)create TABLE T_Enterprise (
    EnterpriseId int not null,
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterChecked char,
    Euserid varchar(50),
    typeid int,
    GGTypeid int,
    GSTypeid int,
    GDTypeid int,
    inserttime datetime,
    isStops char,
    QAmanager varchar(50),
    QAtime datetime,
    PRIMARY KEY (EnterpriseId)
);
CREATE UNIQUE INDEX PK_T_Enterprise ON T_Enterprise (EnterpriseId);
CREATE INDEX CheckName ON T_Enterprise (CheckName);
CREATE INDEX CheckApprovalNo ON T_Enterprise (CheckApprovalNo);
CREATE INDEX CheckEnterrpise ON T_Enterprise (CheckEnterprise);
CREATE INDEX EnterChecked ON T_Enterprise (EnterChecked);
CREATE INDEX EnterpriseArea ON T_Enterprise (EnterpriseArea);
CREATE INDEX typeid ON T_Enterprise (typeid)create TABLE T_EnterpriseArea (
    id int not null,
    EnterpriseId int,
    areano varchar(6),
    inserttime datetime,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_EnterpriseArea ON T_EnterpriseArea (id)create TABLE T_FeaFileInfo (
    feafileid int not null,
    workno varchar(6),
    channelno varchar(9),
    mediatype char,
    filedate varchar(10),
    filename varchar(50),
    isautorec char,
    isautoreced char,
    inserttime datetime,
    PRIMARY KEY (feafileid)
);
CREATE UNIQUE INDEX PK_T_FeaFileInfo ON T_FeaFileInfo (feafileid)create TABLE T_FeaPath (
    id int not null,
    workno varchar(6),
    path varchar(256),
    inserttime datetime,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_FeaPath ON T_FeaPath (id)create TABLE T_FileErrorInfo (
    ID int not null,
    Headid int,
    ErrorInfo nvarchar(256),
    InserPeople nvarchar(50),
    InsertTime datetime,
    XCErrorInfo varchar(250),
    XCInserPeople varchar(50),
    state char,
    XCInserttime varchar(50),
    ChannelNo varchar(9),
    MediaType char,
    FileName varchar(80),
    ChannelName varchar(100),
    BeginTime varchar(8),
    EndTime varchar(8)
)create TABLE T_FileErrorList (
    Id int not null,
    ErrorInfo varchar(256),
    ErrorType char,
    Remark varchar(256),
    InsertTime datetime,
    PRIMARY KEY (Id)
);
CREATE UNIQUE INDEX PK_T_ErrorList ON T_FileErrorList (Id)create TABLE T_FileMinute (
    Headid int,
    Filename varchar(50),
    "Minute" int,
    FileSize varchar(50),
    Inserttime datetime
);
CREATE INDEX IX_T_FileMinute ON T_FileMinute (Headid);
CREATE INDEX IX_T_FileMinute_1 ON T_FileMinute (Filename)create TABLE T_FileNameCGGS (
    headid int not null,
    Filename varchar(50),
    iscut char,
    cutfileinfo varchar(255),
    Cuttime datetime,
    Inserttime datetime
)create TABLE T_FileNameCutTask (
    headid int not null,
    Filename varchar(50),
    iscut char,
    cutfileinfo varchar(255),
    Cuttime datetime,
    Inserttime datetime
)create TABLE T_filepath_ReCut (
    ID int not null,
    filepath varchar(255),
    filename varchar(255),
    feaname varchar(50),
    cutid int,
    inserttime datetime
)create TABLE T_FirstCanton (
    FirstCantonNumber varchar(6) not null,
    FirstCantonName varchar(50) not null
);
CREATE UNIQUE INDEX Firstcantonnumber ON T_FirstCanton (FirstCantonNumber);
CREATE UNIQUE INDEX FirstCantonName ON T_FirstCanton (FirstCantonName)create TABLE T_Ftppath (
    FtpFileId int not null,
    FilePath varchar(256) not null,
    FileName varchar(256) not null,
    SampleId int not null,
    ServerId int not null,
    Link varchar(100) not null,
    SampleType char not null,
    Channelno varchar(10),
    CutDate varchar(6),
    MediaType char,
    InsertTime datetime not null,
    FilePath1 varchar(500),
    BDatetime varchar(20),
    ISGS char,
    isupload char not null,
    PRIMARY KEY (FtpFileId)
);
CREATE UNIQUE INDEX PK_T_Ftppath ON T_Ftppath (FtpFileId)create TABLE T_GDToYJ (
    yjwgid int,
    yjwcord varchar(20),
    gdwgid int,
    gdwcord varchar(20),
    inserttime datetime
)create TABLE T_GSCut (
    channelno varchar(20),
    mediatype varchar(20),
    playdate varchar(80),
    inserttime datetime
)create TABLE T_GSCutList (
    filename varchar(50),
    channelno varchar(50),
    mediatype char,
    iscut char,
    inserttime datetime,
    CutFileInfo varchar(500),
    cuttime datetime,
    headid varchar(50)
)create TABLE T_GSCutlistfilename (
    Filename varchar(50)
)create TABLE T_GSToYJ (
    typeid int,
    yjwgid int,
    yjwcord varchar(20),
    gswgid int,
    gswcord varchar(20),
    inserttime datetime
)create TABLE T_GSToYJAll (
    id int not null,
    typename varchar(20) not null,
    gsdm varchar(20) not null,
    gstext varchar(200) not null,
    yjtext varchar(200) not null,
    xingzhi varchar(50) not null,
    inserttime datetime
)create TABLE T_IllegalDataSet (
    ReportId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckADApprovalNo varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId int,
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    isgouwu char,
    ischeck char,
    isUpload char,
    isHeZuo char,
    isDelete char,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    OutlawLevel varchar(256),
    InsertTime datetime,
    yjtypeid varchar(2),
    yjtypename varchar(20),
    yjillegalitem varchar(30),
    gsjtypeid varchar(10),
    gsjtypename varchar(30),
    gsjillegalitem varchar(40),
    proid int,
    isHZChannel char,
    issee char,
    isdown char,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20),
    IsExport char,
    X1 int,
    Y1 int,
    X2 int,
    Y2 int,
    ratio float,
    acreage float,
    stationname varchar(200)
);
CREATE INDEX IX_T_IllegalDataSet_1 ON T_IllegalDataSet (PlayDate, Channelno, MediaType, headId)create TABLE T_IllegalDataSet_bh (
    ReportId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckADApprovalNo varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId int,
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    isgouwu char,
    ischeck char,
    isUpload char,
    isHeZuo char,
    isDelete char,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    OutlawLevel varchar(256),
    InsertTime datetime,
    yjtypeid varchar(2),
    yjtypename varchar(20),
    yjillegalitem varchar(30),
    gsjtypeid varchar(10),
    gsjtypename varchar(30),
    gsjillegalitem varchar(40),
    proid int,
    isHZChannel char,
    issee char,
    isdown char,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20),
    IsExport varchar(20)
)create TABLE T_JBRight (
    RightId varchar(20) not null,
    RightName varchar(30) not null
)create TABLE T_JBRightZJ (
    RightId varchar(50) not null,
    RightName varchar(50) not null
)create TABLE T_JBUser (
    id int not null,
    userid varchar(50),
    username varchar(50),
    password varchar(50),
    UserArea varchar(500),
    isuse char,
    userType char,
    Backup char,
    DataUpload char,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_JBUser ON T_JBUser (id)create TABLE T_JBUserToArea (
    id int not null,
    userid varchar(50),
    areano char(2),
    inserttime datetime
)create TABLE t_jbusertoareazj (
    id int not null,
    userid varchar(50),
    areano char(2),
    inserttime datetime
)create TABLE T_JBUserToRight (
    UserId varchar(20) not null,
    RightId varchar(20) not null
)create TABLE t_jbusertorightzj (
    UserId varchar(20) not null,
    RightId varchar(20) not null
)create TABLE T_Listlyx (
    id int not null,
    MediaType char,
    Channelno varchar(10),
    ChannelName varchar(256),
    PlayDate datetime,
    InsertTime datetime
)create TABLE T_ListName (
    id int not null,
    listname varchar(50),
    listid int,
    chakan char,
    tongji char
)create TABLE T_Log (
    LogID int not null,
    Userid varchar(100),
    Software varchar(100),
    SoftVersion varchar(100),
    softmodule varchar(100),
    operationname varchar(100),
    Tablename varchar(100),
    M1 varchar(100),
    M2 varchar(100),
    M3 varchar(100),
    M4 varchar(100),
    M5 varchar(100),
    M6 varchar(100),
    M7 varchar(100),
    M8 varchar(100),
    M9 varchar(100),
    M10 varchar(100),
    M11 varchar(100),
    M12 varchar(100),
    M13 varchar(100),
    M14 varchar(100),
    M15 varchar(100),
    M16 varchar(100),
    M17 varchar(100),
    M18 varchar(100),
    M19 varchar(100),
    M20 varchar(100),
    M21 varchar(100),
    M22 varchar(100),
    M23 varchar(100),
    M24 varchar(100),
    M25 varchar(100),
    M26 varchar(100),
    M27 varchar(100),
    M28 varchar(100),
    M29 varchar(100),
    M30 varchar(100),
    M31 varchar(100),
    M32 varchar(100),
    M33 varchar(100),
    M34 varchar(100),
    M35 varchar(100),
    M36 varchar(100),
    M37 varchar(100),
    M38 varchar(100),
    M39 varchar(100),
    M40 varchar(100),
    M41 varchar(100),
    M42 varchar(100),
    M43 varchar(100),
    M44 varchar(100),
    M45 varchar(100),
    Inserttime datetime
)create TABLE T_lognew (
    LOGID bigint not null,
    USERID varchar(50) not null,
    LOGTYPEID varchar(50) not null,
    MOKUAI varchar(50) not null,
    DATAID1 varchar(50),
    DATAID2 varchar(50),
    Mediatype char,
    INSERTIME datetime,
    T1 varchar(100),
    T2 varchar(100),
    T3 varchar(100),
    T4 varchar(100),
    T5 varchar(100),
    T6 varchar(100),
    T7 varchar(100),
    T8 varchar(100),
    T9 varchar(100),
    T10 varchar(100),
    T11 varchar(100),
    T12 varchar(100),
    T13 varchar(100),
    T14 varchar(100),
    T15 varchar(100),
    T16 varchar(100),
    T17 varchar(100),
    T18 varchar(100),
    T19 varchar(100),
    T20 varchar(100),
    T21 varchar(100),
    T22 varchar(100),
    T23 varchar(100),
    T24 varchar(100),
    T25 varchar(100),
    T26 varchar(100),
    T27 varchar(100),
    T28 varchar(100),
    T29 varchar(100),
    T30 varchar(100),
    T31 varchar(255),
    T32 varchar(100),
    T33 varchar(100),
    T34 varchar(100),
    M1 varchar(100),
    M2 varchar(100),
    M3 varchar(100),
    M4 varchar(100),
    M5 varchar(100),
    M6 varchar(100),
    M7 varchar(100),
    M8 varchar(100),
    M9 varchar(100),
    M10 varchar(100),
    M11 varchar(100),
    M12 varchar(100),
    M13 varchar(100),
    M14 varchar(100),
    M15 varchar(100),
    M16 varchar(100),
    M17 varchar(100),
    M18 varchar(100),
    M19 varchar(100),
    M20 varchar(100),
    M21 varchar(100),
    M22 varchar(100),
    M23 varchar(100),
    M24 varchar(100),
    M25 varchar(100),
    M26 varchar(100),
    M27 varchar(100),
    M28 varchar(100),
    M29 varchar(100),
    M30 varchar(100),
    M31 varchar(100),
    M32 varchar(100),
    M33 varchar(100),
    M34 varchar(100)
)create TABLE T_LogTJ (
    logtjID int not null,
    Userid varchar(50),
    Software varchar(50),
    SoftwareVersion varchar(50),
    operationname varchar(100),
    operationmode varchar(50),
    mediatype char,
    tablename varchar(100),
    KHid int,
    Remark varchar(100),
    Inserttime datetime
)create TABLE T_MonitorTask (
    Taskid int not null,
    TaskExplain varchar(50),
    beginTime datetime,
    endTime datetime,
    Operator varchar(50),
    InsertTime datetime
)create TABLE T_NEWSPAPER (
    PaperId varchar(20),
    PaperName varchar(50),
    KanHao varchar(20),
    YouFaiD varchar(50),
    PaperTypeId varchar(10),
    Postingdate varchar(50),
    typeid varchar(10),
    regulatory varchar(100),
    PaperLv varchar(10),
    method varchar(50),
    publicationdate varchar(50),
    CreateMan varchar(50),
    paperareaname varchar(50),
    paperarea varchar(50),
    isstop char not null,
    CreateTime datetime not null,
    remark varchar(255),
    PaperTypeS varchar(30),
    PaperTypeB varchar(30),
    PaperTypeS2 varchar(30),
    QiKan varchar(30)
);
CREATE INDEX papername ON T_NEWSPAPER (PaperName, isstop);
CREATE INDEX paperid ON T_NEWSPAPER (isstop, PaperId);
CREATE INDEX paperarea ON T_NEWSPAPER (paperarea)create TABLE t_newspaper_stopedbackup (
    PaperId varchar(20),
    PaperName varchar(50),
    KanHao varchar(20),
    YouFaiD varchar(50),
    PaperTypeId varchar(10),
    PaperLv varchar(10),
    CreateMan varchar(50),
    CreateTime datetime,
    PaperLvName varchar(50),
    ISJOB char(10),
    SUBMODE varchar(20),
    SUBBTIME varchar(10),
    SUBETIME varchar(10),
    SUBSCRIBER varchar(30),
    CONTACTNO varchar(50),
    PAPERPRIX varchar(20),
    ISSTATION varchar(20),
    ISDY varchar(20),
    ISSTOP char,
    PAPERAREA varchar(10),
    PAPERAREANAME varchar(100),
    PAPERIDCTC varchar(20),
    PAPERREMARK varchar(255),
    ISFAPIAO varchar(10),
    PAPERIDORA varchar(20)
)create TABLE T_NewsPaperDetails (
    LId int not null,
    PaperId varchar(10),
    PaperDate datetime,
    PaperLayout varchar(50),
    AdId varchar(50),
    MediaType char,
    PicId varchar(50),
    MUserId varchar(50),
    TaskId varchar(50),
    IsCheck char,
    IsCommit char,
    IsZJCommit char,
    ZUserId varchar(50),
    ZJCommitTime datetime,
    isupload char,
    IsWorking char,
    InsertTime datetime,
    GSID varchar(50),
    proportion varchar(50),
    X1 int,
    Y1 int,
    X2 int,
    Y2 int,
    ratio float,
    acreage float,
    PRIMARY KEY (LId)
);
CREATE UNIQUE INDEX PK_T_NewsPaperDetails ON T_NewsPaperDetails (LId);
CREATE INDEX PaperID ON T_NewsPaperDetails (PaperId);
CREATE INDEX PaperDate ON T_NewsPaperDetails (PaperDate);
CREATE INDEX Ischeck ON T_NewsPaperDetails (IsCheck);
CREATE INDEX IsCommit ON T_NewsPaperDetails (IsCommit);
CREATE INDEX IsZjCommit ON T_NewsPaperDetails (IsZJCommit);
CREATE INDEX isUpload ON T_NewsPaperDetails (isupload);
CREATE INDEX IsCommitandUpload ON T_NewsPaperDetails (IsCommit, IsZJCommit, isupload);
CREATE INDEX TP_paperidst ON T_NewsPaperDetails (IsCommit, MUserId);
CREATE INDEX picid ON T_NewsPaperDetails (PicId);
CREATE INDEX GSID ON T_NewsPaperDetails (GSID);
CREATE INDEX PK_IDX_T_NewsPaperDetails_WORK_TJ_1 ON T_NewsPaperDetails (IsCommit, InsertTime, X1, X2, PaperId, PicId, MUserId);
CREATE INDEX PK_IDX_T_NewsPaperDetails_WORK_TJ_3 ON T_NewsPaperDetails (IsCommit, X1, X2, PaperId, PicId, MUserId);
CREATE INDEX MediaType ON T_NewsPaperDetails (MediaType)create TABLE T_NewsPaperDirectory (
    GSID int not null,
    PaperId varchar(10),
    PaperName varchar(500),
    PaperDate varchar(50),
    MediaType varchar(50),
    Creatman varchar(50),
    isstop int,
    inserttime datetime,
    isGStask char,
    ischeck char,
    Checkman varchar(500),
    Checktime datetime,
    isupload char,
    uploadtime datetime,
    iswork char,
    isuploadwz char,
    IsSubmit char,
    SubmitTime datetime,
    ISWFSJ char,
    IsYJTask char,
    IsZJ char,
    ZJTime datetime
);
CREATE INDEX TP_paperid ON T_NewsPaperDirectory (PaperDate, PaperId);
CREATE INDEX PK_IDX_T_NewsPaperDirectory_WORK_TJ_1 ON T_NewsPaperDirectory (inserttime, PaperId, Creatman, ischeck);
CREATE INDEX PK_IDX_T_NewsPaperDirectory_WORK_TJ_2 ON T_NewsPaperDirectory (inserttime, PaperId, Creatman, isGStask, IsSubmit, IsYJTask);
CREATE INDEX PK_IDX_T_NewsPaperDirectory_WORK_TJ_3 ON T_NewsPaperDirectory (SubmitTime, PaperId, Creatman, isGStask, IsSubmit, IsYJTask)create TABLE T_NewspaperId (
    NPID varchar(3),
    NPName varchar(50)
)create TABLE T_NewsPaperNoViolation (
    LId int not null,
    PaperId int,
    PaperDate varchar(50),
    CreateTime datetime,
    userid varchar(50)
)create TABLE T_NewsPaperTask (
    TaskId int not null,
    TaskName varchar(256),
    BeginTime datetime,
    EndTime datetime,
    InsertTime datetime,
    PRIMARY KEY (TaskId)
);
CREATE UNIQUE INDEX PK_T_NewsPaperTask ON T_NewsPaperTask (TaskId)create TABLE T_NewsPaperTaskInfo (
    TaskId int not null,
    PaperId varchar(10) not null,
    PaperName varchar(50) not null
)create TABLE T_OperateLog (
    id int not null,
    SoftWare varchar(50),
    SoftWareVertion varchar(50),
    Remark varchar(500),
    ObjectId bigint,
    Operater varchar(50),
    InsertTime datetime,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_OperateLog ON T_OperateLog (id)create TABLE T_OutLawAd (
    adid int,
    outlawid int,
    themeid int,
    inserttime datetime,
    CreateMan varchar(50),
    IsCheck char,
    CheckTime datetime,
    CheckPerson varchar(50)
);
CREATE INDEX OL_Index2_Adid ON T_OutLawAd (adid);
CREATE INDEX PK_ALLINFO ON T_OutLawAd (adid, outlawid, themeid, IsCheck)create TABLE T_OutLawNorm (
    OutlawId int not null,
    OutlawCord varchar(20),
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    Themeid int,
    Typeid varchar(50),
    inserttime datetime,
    PRIMARY KEY (OutlawId)
);
CREATE UNIQUE INDEX PK_T_OutLawNorm ON T_OutLawNorm (OutlawId);
CREATE INDEX OutlawLevel ON T_OutLawNorm (OutlawLevel);
CREATE INDEX Themeid ON T_OutLawNorm (Themeid);
CREATE INDEX Typeid ON T_OutLawNorm (Typeid);
CREATE INDEX theme_type ON T_OutLawNorm (Themeid, Typeid)create TABLE t_OutLawNormGS (
    OutlawId int not null,
    OutlawCord varchar(20),
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    Themeid int,
    Typeid int,
    inserttime datetime
)create TABLE T_OutLawPic (
    PicId int,
    OutlawId int,
    themeid int,
    inserttime datetime
);
CREATE INDEX picid ON T_OutLawPic (PicId);
CREATE INDEX outlawid ON T_OutLawPic (OutlawId);
CREATE INDEX themeid ON T_OutLawPic (themeid);
CREATE INDEX Outlaw ON T_OutLawPic (PicId, OutlawId, themeid)create TABLE T_OutputFileList (
    Lid int not null,
    AreaName varchar(100),
    ChannelName varchar(100),
    Channelnumber varchar(10),
    username varchar(50),
    StartDate varchar(20),
    EndDate varchar(20),
    mediatype varchar(10),
    inserttime datetime
)create TABLE T_PapaerAcreage (
    id int not null,
    PaperId int not null,
    PaperLong int,
    PaperWide int,
    PaperModel varchar(50),
    createman varchar(50),
    remark varchar(255),
    isstop int,
    inserttime datetime
)create TABLE T_paperarea (
    PaperId varchar(20) not null,
    PaperName varchar(50) not null,
    PAPERAREA varchar(10)
)create TABLE T_PaperPic (
    PaperPicId int not null,
    PaperId varchar(10),
    PaperDate datetime,
    PaperLayout varchar(50),
    PaperPicName varchar(100),
    PaperPicPath varchar(500),
    Creattime datetime,
    countspace varchar(50),
    zcspos varchar(500),
    paperinserttime datetime
);
CREATE INDEX paperpic ON T_PaperPic (PaperPicId, PaperId, PaperDate, PaperLayout)create TABLE T_PaperType (
    PaperTypeid int not null,
    PaperTypename varchar(50) not null
)create TABLE T_PlayList (
    ListID bigint not null,
    StartPos varchar(50),
    EndPos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    ZeroCrossMath varchar(50),
    EnergeMatch varchar(50),
    PlayDate varchar(10),
    HeadId int,
    AdId int,
    SampleID int,
    IsHand char,
    iscut char,
    IsCheck char,
    inserttime datetime,
    isupload char,
    isAuto char,
    HandMemo varchar(50),
    IsFlag char
);
CREATE INDEX PK_PLAYLIST_HEADID ON T_PlayList (HeadId);
CREATE INDEX PK_IDX_T_PlayList_2015_2_WorkTJ ON T_PlayList (isAuto, inserttime, HeadId, AdId);
CREATE INDEX PK_IDX_T_PlayList_2015_2_WorkTJ2 ON T_PlayList (inserttime, PlanLen, HeadId, AdId, isAuto);
CREATE INDEX PK_IDX_T_PlayList_2015_2_WorkTJ3 ON T_PlayList (PlayDate, HeadId);
CREATE INDEX PK_IDX_T_PlayList_2015_2_WorkTJ4 ON T_PlayList (PlayDate, HeadId, AdId, isAuto);
CREATE INDEX PK_IDX_T_PlayList_2015_2_WorkTJ5 ON T_PlayList (PlayDate, PlanLen, HeadId, AdId, isAuto);
CREATE INDEX T_PlayList_2015_2_PK_Adid ON T_PlayList (AdId);
CREATE INDEX T_PlayList_2015_2_PK_HeadId ON T_PlayList (HeadId);
CREATE INDEX T_PlayList_2015_2_PK_HeadIdAdId ON T_PlayList (HeadId, AdId);
CREATE INDEX T_PlayList_2015_2_PK_InsertTime ON T_PlayList (inserttime);
CREATE INDEX T_PlayList_2015_2_PK_PlayDate ON T_PlayList (PlayDate);
CREATE INDEX T_PlayList_2015_2_PK_SampleId ON T_PlayList (SampleID);
CREATE INDEX T_PlayList_2015_2_PK_StartEndHeadid ON T_PlayList (StartPos, EndPos, HeadId);
CREATE INDEX PK_PLAYLIST_lid ON T_PlayList (ListID)create TABLE T_PlayListDelLog (
    ListID bigint not null,
    StartPos bigint,
    EndPos bigint,
    PlanLen bigint,
    RealLen bigint,
    HeadId int,
    AdId int,
    SampleID int,
    IsHand char,
    isAuto char,
    MonitorPerson varchar(50),
    inserttime datetime,
    PRIMARY KEY (ListID)
);
CREATE UNIQUE INDEX PK_T_PlayListDelLog ON T_PlayListDelLog (ListID)create TABLE T_PlayListHead (
    HeadId int not null,
    Feaname varchar(100),
    BeginTime varchar(50),
    ConfigFlag varchar(50),
    MediaType char,
    ChannelNo varchar(9),
    PlayListCount varchar(50),
    BeginTimes int,
    Transfered int,
    Seconds int,
    Filepos int,
    IsCut char,
    inserttime datetime,
    Cuttime datetime,
    RightFileName varchar(100),
    IsSubmit char,
    IsGSTask char,
    IsYJTask char,
    IsGDTask char,
    MonitorPerson varchar(50),
    SubmitTime datetime,
    IsCheck char,
    CheckTime datetime,
    CheckPerson varchar(50),
    isUpload char,
    UploadTime datetime,
    CutFileInfo varchar(200),
    Unlock char,
    fileMinite int,
    isBack char,
    ISCut2 char,
    IsAuto char,
    PRIMARY KEY (HeadId)
);
CREATE UNIQUE INDEX PK_T_PlayListHead ON T_PlayListHead (HeadId);
CREATE INDEX playlisthead_index_1 ON T_PlayListHead (MediaType, ChannelNo, BeginTimes);
CREATE INDEX Feaname ON T_PlayListHead (Feaname);
CREATE INDEX PK_CHECK ON T_PlayListHead (BeginTime, ChannelNo, IsSubmit, IsCheck, Feaname)create TABLE T_PlaylistHeadPath (
    ID int not null,
    headid int,
    filename varchar(50),
    filepath varchar(512),
    Inserttime datetime
)create TABLE T_PlayListHeadProblem (
    ID bigint not null,
    headId bigint,
    ShiBieLen int,
    ShiBieCounts int,
    InsertTime datetime,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PK_T_PlayListHeadProblem ON T_PlayListHeadProblem (ID)create TABLE T_PlaylistHeadSee (
    ID int not null,
    Headid varchar(15),
    UserName varchar(50),
    starttime datetime,
    endtime datetime,
    Inserttime datetime
)create TABLE T_ProductPic (
    PicId int not null,
    PicName varchar(256),
    adid int,
    PaperId varchar(10),
    PicPath varchar(512),
    InsertTime datetime,
    PaperPicId int,
    ADcoordinates varchar(512),
    adspace varchar(512),
    listid int
);
CREATE UNIQUE INDEX Picid ON T_ProductPic (PicId, listid)create TABLE T_Programa (
    ProId int not null,
    Programa varchar(100) not null,
    userid varchar(50),
    inserttime datetime
);
CREATE INDEX pk_proid ON T_Programa (ProId)create TABLE T_PROVINCE (
    PROVINCENO varchar(50) not null,
    PROVINCENAME varchar(50),
    AREALEVEL varchar(50)
)create TABLE T_reportidlyx (
    Reportid int
)create TABLE T_Result (
    ReportId int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId varchar(5),
    MediaType char,
    CheckName varchar(256),
    TypeName varchar(50),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId varchar(10),
    Act varchar(256),
    PlayDate datetime,
    IsSex char,
    IllegalItem varchar(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    RulesLevel varchar(20),
    InsertTime datetime,
    ImagePath varchar(256),
    MoveBusiness varchar(10),
    AnnouncementID varchar(10),
    headId int,
    plid int,
    cltime datetime,
    isgouwu char,
    Programa varchar(100),
    ProId varchar(20),
    reportid_nei int,
    issee char,
    sheng varchar(150),
    shi varchar(150),
    xian varchar(150),
    areano varchar(7),
    areaname varchar(150)
);
CREATE INDEX headid_result_index ON T_Result (headId);
CREATE INDEX pk_resIndex1 ON T_Result (PlayDate, ChannelName, AdName);
CREATE INDEX pk_resIndex2 ON T_Result (PlayDate)create TABLE T_Result_huludao (
    ReportId int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId varchar(5),
    MediaType char,
    CheckName varchar(256),
    TypeName varchar(50),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId varchar(10),
    Act varchar(256),
    PlayDate datetime,
    IsSex char,
    IllegalItem varchar(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    RulesLevel char,
    InsertTime datetime,
    ImagePath varchar(256),
    MoveBusiness varchar(10),
    AnnouncementID varchar(10),
    headId int,
    plid int,
    cltime datetime,
    isgouwu char(10)
)create TABLE T_SamFeaInfo (
    ID int not null,
    ChannelNo varchar(20),
    MediaType char,
    FeaSavePath varchar(500),
    ADMinTime varchar(50),
    ADMaxTime varchar(50),
    ThickEnergeCore varchar(50),
    ThickFrequencyCore varchar(50),
    MinEnergeDegree varchar(50),
    MinFrequencyDegree varchar(50),
    Inserttime datetime
)create TABLE T_Sample (
    SampleID int not null,
    MediaType varchar(50),
    ChannelNo varchar(9),
    SampleFile varchar(256),
    FeatureFile varchar(256),
    SamDate varchar(10),
    SamBPos varchar(50),
    SamEPos varchar(50),
    SampleLen varchar(50),
    CreateTime varchar(50),
    FileName varchar(50),
    LastTime varchar(50),
    AdId int,
    inserttime datetime,
    iscut char,
    samcheck char,
    isstop char,
    LID int,
    CreateMan varchar(20),
    CheckMan varchar(20),
    CheckTime datetime,
    IsReport char,
    ReportTime datetime,
    StopMan varchar(20),
    PRIMARY KEY (SampleID)
);
CREATE UNIQUE INDEX PK_T_Sample ON T_Sample (SampleID);
CREATE INDEX PK_T_Sample1 ON T_Sample (ChannelNo, MediaType, AdId);
CREATE INDEX Index_Sample_Adid ON T_Sample (AdId);
CREATE INDEX SAM_PlayList ON T_Sample (FileName, SamBPos, SamEPos);
CREATE INDEX LID ON T_Sample (LID);
CREATE INDEX PK_ZJ ON T_Sample (ChannelNo, SamDate, AdId, samcheck, isstop, FileName);
CREATE INDEX IX_T_Sample ON T_Sample (ChannelNo, isstop);
CREATE INDEX PK_IDX_Sample_WorkTJ001 ON T_Sample (inserttime, AdId)create TABLE T_Samplepath (
    SId int not null,
    FilePath varchar(256) not null,
    FTPFilePath varchar(256),
    FileName varchar(50),
    SampleId int not null,
    ServerId int not null,
    Reallen varchar(200),
    SfileName varchar(200),
    SampleType char,
    Channelno varchar(10),
    CutDate varchar(6),
    MediaType char,
    InsertTime datetime,
    Reallen1 varchar(50),
    BDatetime varchar(20),
    ISGS char,
    isupload char not null,
    PRIMARY KEY (SId)
);
CREATE UNIQUE INDEX PK_T_Samplepath ON T_Samplepath (SId);
CREATE INDEX PK_T_Samplepath2 ON T_Samplepath (SampleId, MediaType)create TABLE T_SampleProblem (
    ID bigint not null,
    headId bigint,
    AdId bigint,
    SampleId bigint,
    ShiBieLen int,
    ShiBieCounts int,
    InsertTime datetime,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PK_T_SampleProblem ON T_SampleProblem (ID)create TABLE T_SecondCanton (
    FirstCantonNumber varchar(6) not null,
    SecondCantonNumber varchar(6) not null,
    SecondCantonName varchar(50) not null
);
CREATE UNIQUE INDEX SecondCantonNumber ON T_SecondCanton (SecondCantonNumber);
CREATE INDEX FirstCantonNumber ON T_SecondCanton (FirstCantonNumber);
CREATE INDEX SecondCantonNmae ON T_SecondCanton (SecondCantonName);
CREATE UNIQUE INDEX First-Second ON T_SecondCanton (FirstCantonNumber, SecondCantonNumber)create TABLE T_SeriousResult (
    ReportId int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId varchar(5),
    MediaType char,
    TypeName varchar(50),
    PlayDate datetime,
    IllegalItem varchar(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    InsertTime datetime,
    ImagePath varchar(256),
    Rid varchar(50),
    headId int,
    plid int,
    ConductTime datetime,
    OutlawLevel varchar(50),
    Version varchar(256),
    ChannelType varchar(50),
    remark char,
    issee char,
    seetime datetime,
    report_id_new int,
    url1 varchar(256),
    ProId varchar(20),
    Programa varchar(100),
    ReportId_nei int,
    areaname1 varchar(255),
    areano varchar(10),
    sheng varchar(100),
    shi varchar(100),
    xian varchar(100),
    arealevel varchar(20),
    stationname varchar(200),
    IsLADC char,
    acreage float,
    ChannelTypeS varchar(50),
    isws char
);
CREATE INDEX PK1 ON T_SeriousResult (PlayDate)create TABLE T_ServerIPList (
    ID int not null,
    SoftWareName nvarchar(50),
    ServerIP nvarchar(50),
    IsStop char,
    CreateMan nvarchar(50),
    PassWord nvarchar(20),
    Inserttime datetime
)create TABLE T_ServerList (
    ID int not null,
    IPAddress varchar(50),
    IPAddress2 varchar(50),
    IPAddress3 varchar(50),
    IPAddress4 varchar(50),
    ISSTOP char,
    CreateMan varchar(50),
    Inserttime datetime
)create TABLE T_ServerObject (
    id int not null,
    begintime varchar(10),
    endtime varchar(10),
    productname varchar(150),
    programname varchar(150),
    enterprise varchar(250),
    inserttime datetime
)create TABLE T_ServerState (
    ID int not null,
    SystemVersion varchar(50),
    ServerIP varchar(20),
    CPU int,
    RAM int,
    C float,
    D float,
    E float,
    F float,
    G float,
    H float,
    I float,
    J float,
    K float,
    L float,
    M float,
    N float,
    O float,
    P float,
    Q float,
    R float,
    S float,
    T float,
    U float,
    V float,
    W float,
    X float,
    Y float,
    Z float,
    Version varchar(15),
    Inserttime datetime
)create TABLE t_shenyangwanbao20140917h (
    MediaType char,
    PaperId varchar(10),
    PaperName varchar(50),
    AdId varchar(50),
    ADName varchar(256),
    Version varchar(256),
    PaperDate datetime,
    PaperLayout varchar(50),
    parenttypeid varchar(50) not null,
    parenttypename varchar(50) not null,
    sontypeid varchar(50),
    sontypename varchar(50) not null,
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    PicId varchar(50),
    PicPath varchar(512),
    Lid int not null,
    ADDescribe varchar(8000),
    programa varchar(100),
    ProId int,
    paperarea varchar(50),
    areaname varchar(50),
    PROVINCENAME nvarchar(16),
    CITYNAME nvarchar(50),
    COUNTRYNAME nvarchar(30),
    channeltype varchar(30)
)create TABLE T_SoftwareVersion (
    ID int not null,
    SoftName varchar(50),
    Version varchar(20),
    UpdateIni varchar(100)
)create TABLE T_StationTask (
    id int not null,
    MediaNo varchar(10),
    MediaType char,
    TaskExplain varchar(100),
    TaskLevel char,
    BeginTime varchar(10),
    EndTime varchar(10),
    InsertTime datetime,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX PK_T_StationTask ON T_StationTask (id)create TABLE T_StreamServer (
    ServerId int not null,
    Ip varchar(20) not null,
    IpType varchar(10) not null,
    Port int not null
)create TABLE T_T_ADDataSet_bh (
    LId int not null,
    MediaType char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    AdId int not null,
    AdName varchar(256) not null,
    Version varchar(256),
    PlayDate datetime not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    ADDescribe varchar(256),
    Programa varchar(256),
    channeltype varchar(50),
    InsertTime datetime,
    proid int,
    areaname varchar(100),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    areano varchar(7),
    AREALEVEL varchar(20)
);
CREATE INDEX IX_T_ADDataSet ON T_T_ADDataSet_bh (headId, PlayDate, Channelno, MediaType)create TABLE T_TaskInfo (
    Taskid int not null,
    Mediatype char not null,
    ChannelNo varchar(10) not null
)create TABLE T_TaskSchedule (
    Id int not null,
    nDate date,
    YJTask char,
    GSTask char,
    InsertTime datetime,
    PRIMARY KEY (Id)
);
CREATE UNIQUE INDEX PK_T_TaskSchedule ON T_TaskSchedule (Id)create TABLE T_Theme (
    ThemeId int not null,
    ThemeName varchar(10) not null,
    PRIMARY KEY (ThemeId)
);
CREATE UNIQUE INDEX PK_T_Theme ON T_Theme (ThemeId)create TABLE T_ThreeCanton (
    SecondCantonNumber varchar(6) not null,
    ThreeCantonNumber varchar(6) not null,
    ThreeCantonName varchar(50) not null
);
CREATE UNIQUE INDEX ThreeCantonNumber ON T_ThreeCanton (ThreeCantonNumber);
CREATE INDEX SeconcCantonNumber ON T_ThreeCanton (SecondCantonNumber);
CREATE INDEX ThreeCantonName ON T_ThreeCanton (ThreeCantonName);
CREATE INDEX Second-Three ON T_ThreeCanton (SecondCantonNumber, ThreeCantonNumber)create TABLE T_Type (
    TypeId varchar(50) not null,
    ParentID varchar(50) not null,
    TypeName varchar(50) not null,
    Remark varchar(200),
    ThemeId int,
    inserttime datetime,
    InsertMan varchar(20)
);
CREATE INDEX PK_TYPE ON T_Type (TypeId, ParentID, TypeName, ThemeId)create TABLE T_TypeCorresponding (
    id int not null,
    GGTypeid varchar(10) not null,
    GSTypename varchar(20),
    YJTypename varchar(20),
    inserttime datetime not null
)create TABLE T_TypeWeb (
    TypeId varchar(50) not null,
    ParentID varchar(50) not null,
    TypeName varchar(50) not null,
    Remark varchar(200),
    ThemeId int,
    inserttime datetime
)create TABLE t_typeys (
    AdName varchar(256),
    TypeName varchar(50),
    TypeId varchar(5)
)create TABLE T_USERINFO (
    USERID varchar(50) not null,
    USERNAME varchar(50),
    PASSWORD varchar(50) not null,
    ISSTOP varchar(1),
    ISADMIN varchar(1),
    CREATER varchar(50),
    INSERTTIME datetime
)create TABLE T_UserLoginGS (
    UserLoginId int not null,
    UserName varchar(50),
    PassWord varchar(50),
    UserType varchar(10),
    ShowBeginTime varchar(20),
    ShowEndTime varchar(20),
    LoginTime varchar(20),
    AreaName varchar(256),
    IsOpen char not null,
    creater varchar(50)
)create TABLE T_USERRIGHTS (
    USERID varchar(50) not null,
    RIGHTSID varchar(50) not null,
    INSERTTIME datetime
)create TABLE T_Variables (
    ID int not null,
    SoftWareName varchar(50),
    VariableName varchar(50),
    VariableValue varchar(500),
    Inserttime datetime
)create TABLE T_WGXMatching (
    id int not null,
    themeid int not null,
    gswgid int not null,
    yjwgid int not null,
    gdwg int not null,
    inserttime datetime not null
)create TABLE T_YJFilelist (
    ID int not null,
    FileName varchar(50),
    Channelno varchar(10),
    Playdate varchar(20),
    Mediatype char,
    IsCut char,
    CutFileInfo varchar(500),
    Cuttime datetime,
    Inserttime datetime
)create TABLE T_YJTOGSOutlaw (
    id int not null,
    YJTypeid varchar(20),
    YJOutlawid int,
    GSTypeid varchar(20) not null,
    GSOutlawid int not null,
    GDTypeid varchar(20),
    GDOutlawid int,
    inserttime datetime not null
)create TABLE T_ZJUser (
    id int not null,
    userid varchar(50),
    username varchar(50),
    password varchar(50),
    UserRole varchar(200),
    isuse char,
    department varchar(50),
    inserttime date,
    stoptime date,
    UserArea varchar(200),
    UserType varchar(200)
)create TABLE tempa (
    Channelno varchar(10),
    ChannelName varchar(256),
    MediaType char,
    PlayDate datetime
)create TABLE tempabc (
    mediatype varchar(50),
    Channelno varchar(9),
    ChannelName nvarchar(255),
    PlayDate varchar(10),
    AdName varchar(256),
    Version varchar(256),
    RunEnterprise varchar(256),
    planlen numeric(19),
    ParentTypeId varchar(50) not null,
    ParentTypeName varchar(50) not null,
    SonTypeId varchar(50),
    SonTypeName varchar(50) not null,
    provincename nvarchar(16),
    cityname nvarchar(50),
    countryname nvarchar(30),
    adcount int
)create TABLE tempb (
    mediatype char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    PlayDate datetime not null,
    AdName varchar(256) not null,
    Version varchar(256),
    RunEnterprise varchar(256),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    adcount int
)create TABLE tempb1 (
    mediatype char not null,
    Channelno varchar(10) not null,
    ChannelName varchar(256) not null,
    PlayDate datetime not null,
    AdName varchar(256) not null,
    Version varchar(256),
    RunEnterprise varchar(256),
    PlayLean varchar(50) not null,
    ParentTypeId varchar(7),
    ParentTypeName varchar(50),
    SonTypeId varchar(7),
    SonTypeName varchar(50),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    adcount int
)create TABLE tempheaid (
    headid int not null
)create TABLE tmpaaa (
    Channelno varchar(10) not null,
    AdName varchar(256) not null,
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId varchar(1) not null,
    gsjTypeId varchar(10),
    MediaType char not null,
    gsjTypeName varchar(30),
    PlayDate datetime not null,
    gsjIllegalItem varchar(40),
    AdId int not null,
    ChannelName varchar(256) not null,
    PlayLean varchar(50) not null,
    SampleId int,
    SampleType char,
    ImagePath varchar(256),
    headId int,
    plid int,
    OutlawLevel varchar(256),
    Version varchar(256),
    ChannelType varchar(50),
    Programa varchar(256),
    ProId int,
    ReportId int not null,
    areaname varchar(100),
    areano varchar(7),
    provincename varchar(30),
    cityname varchar(50),
    countryname varchar(50),
    arealevel varchar(20),
    acreage float,
    stationname varchar(200)
)create TABLE TP_NEWSPAPER (
    PAPERID varchar(20),
    PAPERNAME varchar(50),
    KANHAO varchar(20),
    YOUFAID varchar(20),
    PAPERTYPEID varchar(10),
    PAPERLV varchar(10),
    CREATEMAN varchar(20),
    CREATETIME datetime,
    PAPERLVNAME varchar(10),
    ISJOB varchar(1),
    SUBMODE varchar(20),
    SUBBTIME varchar(10),
    SUBETIME varchar(10),
    SUBSCRIBER varchar(30),
    CONTACTNO varchar(50),
    PAPERPRIX varchar(20),
    ISSTATION varchar(20),
    ISDY varchar(20),
    ISSTOP char,
    PAPERAREA varchar(10),
    PAPERAREANAME varchar(100),
    PAPERIDCTC varchar(20),
    PAPERREMARK varchar(255),
    ISFAPIAO varchar(10)
)create TABLE TP_NEWSPAPER20130617 (
    PAPERID varchar(20) not null,
    PAPERNAME varchar(50) not null,
    KANHAO varchar(20),
    YOUFAID varchar(20),
    PAPERTYPEID varchar(10) not null,
    PAPERLV varchar(10) not null,
    CREATEMAN varchar(20) not null,
    CREATETIME datetime not null,
    PAPERLVNAME varchar(10),
    ISJOB varchar(1),
    SUBMODE varchar(20),
    SUBBTIME varchar(10),
    SUBETIME varchar(10),
    SUBSCRIBER varchar(30),
    CONTACTNO varchar(50),
    PAPERPRIX varchar(20),
    ISSTATION varchar(20),
    ISDY varchar(20),
    ISSTOP char,
    PAPERAREA varchar(10),
    PAPERAREANAME varchar(100),
    PAPERIDCTC varchar(20),
    PAPERREMARK varchar(255),
    ISFAPIAO varchar(10),
    PAPERIDORA varchar(20)
)create TABLE TP_paperbanners (
    bannersid int not null,
    bannersname varchar(500),
    bannerspath varchar(500),
    paperid varchar(50),
    isstop varchar(1),
    INSERTTIME datetime,
    publicationdate varchar(50)
)create TABLE TP_PAPERDETAILS (
    PAPERID varchar(20) not null,
    PAPERDATEID varchar(20) not null,
    PAPERDATE varchar(50) not null,
    DATENM varchar(20),
    ALLDATENM varchar(20) not null,
    YSBANSHU varchar(10),
    SJBANSHU varchar(10),
    CREATEMAN varchar(20) not null,
    CREATETIME datetime not null,
    ISSCAN varchar(1) not null,
    SCANMAN varchar(20)
);
CREATE INDEX PAPERID ON TP_PAPERDETAILS (PAPERID);
CREATE INDEX PAPERDATEID ON TP_PAPERDETAILS (PAPERDATEID);
CREATE INDEX CREATEMAN ON TP_PAPERDETAILS (CREATEMAN);
CREATE INDEX ISSCAN ON TP_PAPERDETAILS (ISSCAN);
CREATE INDEX ID_Date ON TP_PAPERDETAILS (PAPERID, PAPERDATE);
CREATE INDEX ID_Date_No ON TP_PAPERDETAILS (PAPERID, PAPERDATEID, PAPERDATE)create TABLE TP_PAPERKD (
    STATIONNO varchar(10) not null,
    STATIONNAME varchar(50) not null,
    KDNAME varchar(255),
    KDTYPE varchar(10),
    KDJG numeric(8),
    PAPERNAME varchar(255),
    INSERTTIME datetime not null,
    ISFP1 char,
    KD_ID int not null,
    ISFP varchar(255),
    KDDATE varchar(20),
    FPDATE varchar(20),
    FPPROJECT varchar(255),
    CreateMan varchar(50)
);
CREATE UNIQUE INDEX KD_ID ON TP_PAPERKD (KD_ID);
CREATE INDEX stationno ON TP_PAPERKD (STATIONNO);
CREATE INDEX STATIONNAME ON TP_PAPERKD (STATIONNAME);
CREATE INDEX KDNAME ON TP_PAPERKD (KDNAME);
CREATE INDEX KDTYPE ON TP_PAPERKD (KDTYPE)create TABLE TP_PAPERKD_BACKUP20131007 (
    STATIONNO varchar(10) not null,
    STATIONNAME varchar(50) not null,
    KDNAME varchar(255) not null,
    KDTYPE varchar(10),
    KDJG numeric(8),
    PAPERNAME varchar(255),
    INSERTTIME datetime not null,
    ISFP1 char,
    KD_ID int not null,
    ISFP varchar(255),
    KDDATE datetime,
    FPDATE datetime,
    FPPROJECT varchar(255),
    CreateMan varchar(50)
)create TABLE TP_PAPERTYPE (
    PAPERTYPEID int not null,
    PAPERTYPE varchar(50) not null
)create TABLE TP_RIGHT (
    RIGHTID varchar(20) not null,
    RIGHTNAME varchar(20) not null,
    RIGHTTYPE varchar(1)
)create TABLE TP_subscribe (
    id int not null,
    subyears varchar(10),
    paperareano varchar(10),
    paperareaname varchar(100),
    paperid varchar(50),
    papername varchar(50),
    KanHao varchar(50),
    YouFaiD varchar(50),
    paperlv varchar(50),
    SUBMODE varchar(20),
    SUBBTIME varchar(50),
    SUBETIME varchar(50),
    SUBSCRIBER varchar(30),
    CONTACTNO varchar(50),
    stationname varchar(50),
    taskname varchar(50),
    unitprice varchar(50),
    subprice varchar(50),
    bxtprice varchar(50),
    remark varchar(8000),
    ischeck varchar(1),
    inserttime datetime,
    isfapiao varchar(20),
    bannersid int,
    taskid int
)create TABLE TP_subscribe_2014 (
    id int not null,
    subyears varchar(10),
    paperareano varchar(10),
    paperareaname varchar(100),
    paperid varchar(50),
    papername varchar(50),
    KanHao varchar(50),
    YouFaiD varchar(50),
    paperlv varchar(50),
    SUBMODE varchar(20),
    SUBBTIME varchar(50),
    SUBETIME varchar(50),
    SUBSCRIBER varchar(30),
    CONTACTNO varchar(50),
    stationname varchar(50),
    taskname varchar(50),
    unitprice varchar(50),
    subprice varchar(50),
    bxtprice varchar(50),
    remark varchar(8000),
    ischeck varchar(1),
    inserttime datetime,
    isfapiao varchar(20),
    bannersid int,
    taskid int
)create TABLE TP_type (
    typeid int not null,
    typename varchar(50),
    inserttime datetime
)create TABLE TP_USER (
    USERID varchar(20) not null,
    USERNAME varchar(20) not null,
    UPASSWORD varchar(20) not null,
    CREATEMAN varchar(20) not null,
    CREATETIME datetime not null,
    ISUSES numeric(1) not null,
    LOGINSYS char
)create TABLE TP_USERTORIGHT (
    USERID varchar(20) not null,
    RIGHTID varchar(20) not null
)create TABLE TP_WAREHOUSE (
    PAPERID varchar(20) not null,
    PAPERDATEID varchar(20) not null,
    PAPERDATE varchar(50) not null,
    DATENM varchar(20),
    ALLDATENM varchar(20) not null,
    YSBANSHU varchar(10),
    SJBANSHU varchar(10),
    CREATEMAN varchar(20) not null,
    CREATETIME datetime not null,
    PKMAN varchar(20) not null,
    RKTIME datetime not null,
    ISJY varchar(1) not null,
    SHELFID varchar(20),
    PICPATH varchar(100),
    ISPIC numeric(1)
);
CREATE INDEX paperdate ON TP_WAREHOUSE (PAPERDATE);
CREATE INDEX paperid ON TP_WAREHOUSE (PAPERID);
CREATE INDEX paperdateid ON TP_WAREHOUSE (PAPERDATEID);
CREATE INDEX createman ON TP_WAREHOUSE (CREATEMAN);
CREATE INDEX ID_Date ON TP_WAREHOUSE (PAPERID, PAPERDATE);
CREATE INDEX ID_Date_NO ON TP_WAREHOUSE (PAPERID, PAPERDATEID, PAPERDATE);
CREATE INDEX RKTIME ON TP_WAREHOUSE (RKTIME);
CREATE INDEX CreateTime ON TP_WAREHOUSE (CREATETIME)create VIEW FTPtoStream (
    FilePath varchar(256) not null,
    FileName varchar(50),
    InsertTime datetime,
    Expr1 varchar(256) not null,
    Expr2 varchar(256) not null,
    Expr3 datetime not null,
    FtpFileId int not null
)create VIEW temp_ctcplaylist (
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(100),
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95),
    ADName varchar(256),
    PlanLen int,
    RealLen int,
    Version varchar(256),
    remark varchar(256),
    Enterprise varchar(256),
    Act varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    ADApprovalNo varchar(256),
    AREANAME varchar(100) not null,
    AdId int,
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    Brand varchar(256)
)create VIEW test1 (
    AdId int not null,
    ADName varchar(256),
    IsStop char,
    SampleID int not null,
    ChannelNo varchar(9),
    samisstop char,
    inserttime datetime,
    saminserttime datetime
)create VIEW V_ADAllCount (
    ChannelName varchar(100),
    ChannelNo varchar(9),
    MediaType char,
    Feaname varchar(100),
    AdId int,
    typeid int,
    TypeName varchar(50) not null,
    ThemeName varchar(10) not null,
    PlayDate varchar(10)
)create VIEW V_AdEnterorise (
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    MediaType varchar(4) not null,
    remark varchar(256),
    Act varchar(256),
    IsStop char,
    remark2 varchar(256),
    IsSex varchar(2) not null,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    inserttime datetime,
    IllegalNature varchar(4) not null,
    TypeName varchar(50)
)create VIEW V_AdInfo (
    StationId int not null,
    ChannelNo varchar(9),
    FeaSavePath varchar(256),
    SampleID int not null,
    SampleFile varchar(256),
    FeatureFile varchar(256),
    SampleLen varchar(50),
    CreateTime varchar(50),
    LastTime varchar(50),
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    Enterprise varchar(256),
    remark varchar(256),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    IsStop char,
    CheckName varchar(256),
    remark2 varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    MediaType varchar(50),
    EnterpriseId varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    samcheck char
)create VIEW V_ADTypeInfo (
    adid int,
    ggbtypeid varchar(6),
    ggbtypename varchar(50),
    ggtypeid varchar(50),
    ggtypename varchar(50),
    yjtypeid varchar(50),
    yjtypenamee varchar(50),
    gstypeid varchar(50),
    gstypename varchar(50)
)create VIEW V_ADWG (
    adid int,
    outlawid int,
    OutlawCord varchar(20),
    TypeName varchar(50) not null,
    ThemeName varchar(10) not null,
    OutlawLevel varchar(50),
    OutlawNorm varchar(500),
    OutlawName varchar(500),
    ThemeId int not null,
    TypeId varchar(50) not null
)create VIEW V_AllAdInfo (
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    Enterprise varchar(256),
    remark varchar(256),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    IsStop char,
    CheckName varchar(256),
    remark2 varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    MediaType varchar(50),
    EnterpriseId varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    CheckADApprovalNo varchar(256)
)create VIEW V_AllChannelPlayList (
    ListID int not null,
    StartPos varchar(50),
    EndPos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    ZeroCrossMath varchar(50),
    EnergeMatch varchar(50),
    PlayDate varchar(10),
    HeadId int,
    AdId int,
    SampleID int,
    IsHand char,
    iscut char,
    IsCheck char,
    inserttime datetime,
    isupload char,
    isAuto char,
    Feaname varchar(100),
    BeginTime varchar(50),
    ConfigFlag varchar(50),
    MediaType char,
    ChannelNo varchar(9),
    PlayListCount varchar(50),
    BeginTimes int,
    Transfered int,
    Seconds int,
    Filepos int,
    IsCut2 char,
    inserttime2 datetime
)create VIEW V_AllPlayerInfo (
    AdId int,
    MediaType char,
    SampleId varchar(256),
    SampleType char,
    FilePath varchar(256),
    ImagePath varchar(256),
    FileName varchar(50)
)create VIEW V_AREAINFO (
    AREANO varchar(50),
    AREANAME varchar(1050),
    PROVINCENAME varchar(50),
    CITYName varchar(500),
    COUNTYName varchar(500)
)create VIEW V_AreaInfo1 (
    AREANO varchar(6) not null,
    AREANAME varchar(100) not null,
    PROVINCENAME varchar(50) not null,
    CITYNAME varchar(50) not null,
    COUNTYNAME varchar(50) not null
)create VIEW V_AreaInfoMation (
    areano varchar(50),
    AREANAME varchar(1050),
    FirstCantonName varchar(50),
    SecondCantonName varchar(500),
    ThreeCantonName varchar(500)
)create VIEW V_AreaInfoMation1 (
    AREANO varchar(6) not null,
    AREANAME varchar(150) not null,
    FirstCantonName varchar(50) not null,
    SecondCantonName varchar(50) not null,
    ThreeCantonName varchar(50) not null
)create VIEW V_AreaLevels (
    AREANO varchar(6) not null,
    AREANAME varchar(50) not null,
    Levels varchar(4) not null
)create VIEW V_ChannelAdInfo (
    AdId int not null,
    ADName varchar(256),
    ChannelNo varchar(9),
    typeid int,
    themeid int,
    TypeName varchar(50) not null,
    Version varchar(256),
    Brand varchar(256),
    MediaType varchar(50),
    Act varchar(256),
    IsSex char,
    CheckName varchar(256),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    remark varchar(256),
    remark2 varchar(256),
    EnterpriseId varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256)
)create VIEW V_ConductResult (
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    TypeName varchar(50) not null,
    ConductId varchar(50),
    username varchar(50),
    is_stop char,
    usertype varchar(50),
    inserttime datetime,
    ThemeId int
)create VIEW V_ctcchongfu (
    ChannelNo varchar(9),
    ADName varchar(256),
    MediaType char,
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95)
)create VIEW V_ctcchongfu2 (
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(100),
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95),
    ADName varchar(256),
    ListID int not null
)create VIEW V_CTCPlayList (
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(256),
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95),
    ADName varchar(256),
    spos varchar(50),
    epos varchar(50),
    PlanLen int,
    RealLen int,
    EnergeMatch varchar(50),
    ZeroCrossMath varchar(50),
    Version varchar(256),
    Brand varchar(256),
    remark varchar(600),
    Enterprise varchar(256),
    Kind char,
    Act varchar(256),
    Director varchar(256),
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    AdId int,
    ListID int not null,
    Feaname varchar(100),
    HeadId int not null,
    ischeck char,
    pcheck char,
    IsHand char,
    SampleID int
)create VIEW V_CTCPlayList22 (
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(256),
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95),
    ADName varchar(256),
    spos varchar(50),
    epos varchar(50),
    PlanLen int,
    RealLen int,
    EnergeMatch varchar(50),
    ZeroCrossMath varchar(50),
    Version varchar(256),
    Brand varchar(256),
    remark varchar(600),
    Enterprise varchar(256),
    Kind char,
    Act varchar(256),
    Director varchar(256),
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    AdId int,
    ListID int not null,
    Feaname varchar(100),
    HeadId int not null,
    ischeck char,
    pcheck char,
    IsHand char,
    SampleID int
)create VIEW V_File (
    FileName varchar(256) not null,
    FileName2 varchar(50) not null,
    FilePath varchar(256) not null,
    FilePath2 varchar(256) not null,
    FilePath3 varchar(8000),
    FilePath5 varchar(256)
)create VIEW V_FTP (
    FtpFileId int,
    FilePath varchar(256),
    FileName varchar(256),
    SampleId int,
    ServerId int,
    Link varchar(100),
    SampleType char,
    InsertTime datetime,
    Channelno varchar(10),
    cutdate varchar(6),
    MediaType char
)create VIEW V_NewsPaperArea (
    PaperId varchar(20),
    PaperName varchar(50),
    areaname varchar(50) not null,
    PaperLv varchar(10),
    PAPERAREA varchar(10)
)create VIEW V_NoSample (
    ListID int not null,
    StartPos varchar(50),
    EndPos varchar(50),
    RealLen varchar(50),
    PlayDate varchar(10),
    iscut char,
    Feaname varchar(100),
    MediaType char,
    AdId int not null,
    ADName varchar(256),
    SampleID int,
    ChannelNo varchar(9),
    ChannelName varchar(100)
)create VIEW V_OutLaw (
    adid int,
    themeid int,
    OutlawId int not null,
    OutlawCord varchar(20),
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    Typeid varchar(50),
    TypeName varchar(50) not null,
    IsCheck char
)create VIEW V_OutLawInfo (
    adid int,
    themeid int,
    OutlawId int not null,
    OutlawCord varchar(20),
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    typeid varchar(50),
    TypeName varchar(50) not null
)create VIEW V_OutLawPic (
    OutlawId int not null,
    PicId int,
    OutlawCord varchar(20),
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    TypeName varchar(50) not null,
    Typeid int,
    themeid int
)create VIEW V_PaperResult (
    PaperName varchar(50) not null,
    PaperLvName varchar(50) not null,
    PaperId varchar(20) not null,
    PaperDate datetime,
    PaperLayout varchar(50),
    AdId varchar(50),
    ADName varchar(256),
    Version varchar(256),
    Enterprise varchar(256),
    remark varchar(256),
    Act varchar(256),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckADApprovalNo varchar(256),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    IsSex char,
    LId int not null,
    PicId varchar(50),
    MUserId varchar(50),
    ZUserId varchar(50)
)create VIEW V_PlAdInfo (
    HeadId int not null,
    Feaname varchar(100),
    BeginTime varchar(50),
    MediaType char,
    ChannelNo varchar(9),
    ListID int not null,
    StartPos varchar(50),
    EndPos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    ZeroCrossMath varchar(50),
    EnergeMatch varchar(50),
    PlayDate varchar(10),
    AdId int,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    Enterprise varchar(256),
    remark varchar(256),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    IsCheck char,
    inserttime datetime,
    IsStop char,
    remark2 varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256)
)create VIEW V_play (
    Channelno varchar(10),
    SampleId varchar(10),
    SampleType char,
    cutdate varchar(6),
    MediaType char
)create VIEW V_PlayList---- (
    ListID int not null,
    ADName varchar(256),
    StartPos varchar(50),
    EndPos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    ZeroCrossMath varchar(50),
    EnergeMatch varchar(50),
    PlayDate varchar(10),
    Version varchar(256),
    Brand varchar(256),
    HeadId int,
    remark varchar(256),
    Act varchar(256),
    AdId int not null,
    IsCheck char,
    Feaname varchar(100),
    ChannelNo varchar(9),
    ChannelName varchar(100),
    SampleID int,
    remark2 varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    MediaType varchar(50),
    IsHand char,
    inserttime datetime,
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    IsStop char,
    isupload char,
    TypeName varchar(50) not null,
    themeid int,
    typeid varchar(50),
    Director varchar(256)
)create VIEW V_PLAYLISTINFO (
    ChannelNo varchar(9),
    MediaType char,
    PlayDate varchar(10),
    StartPos varchar(10),
    EndPos varchar(10),
    ADName varchar(256),
    spos varchar(50),
    epos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    EnergeMatch varchar(50),
    ZeroCrossMath varchar(50),
    Version varchar(256),
    Brand varchar(256),
    remark varchar(600),
    Enterprise varchar(256),
    Kind char,
    Act varchar(256),
    Director varchar(256),
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    AdId int,
    ListID bigint not null,
    Feaname varchar(100),
    HeadId int not null,
    ischeck char,
    pcheck char,
    IsHand char,
    SampleID int,
    BeginTime varchar(50),
    HeadCheck char,
    SubmitTime datetime,
    ProId int,
    Programa varchar(100),
    PROVINCENAME varchar(50),
    IsSubmit char,
    HandMemo varchar(50),
    inserttime datetime
)create VIEW V_PLAYLISTINFO2 (
    ChannelNo varchar(9),
    MediaType char,
    PlayDate varchar(10),
    StartPos varchar(8000),
    EndPos varchar(8000),
    ADName varchar(256),
    spos varchar(50),
    epos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    EnergeMatch varchar(50),
    ZeroCrossMath varchar(50),
    Version varchar(256),
    Brand varchar(256),
    remark varchar(600),
    Enterprise varchar(256),
    Kind char,
    Act varchar(256),
    Director varchar(256),
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    AdId int,
    ListID int not null,
    Feaname varchar(100),
    HeadId int not null,
    ischeck char,
    pcheck char,
    IsHand char,
    SampleID int,
    BeginTime varchar(50),
    HeadCheck char,
    SubmitTime datetime,
    ProId int,
    Programa varchar(100)
)create VIEW V_PLAYLISTINFO3 (
    ChannelNo varchar(9),
    MediaType char,
    PlayDate varchar(10),
    StartPos varchar(10),
    EndPos varchar(10),
    ADName varchar(256),
    spos varchar(50),
    epos varchar(50),
    PlanLen varchar(50),
    RealLen varchar(50),
    EnergeMatch varchar(50),
    ZeroCrossMath varchar(50),
    Version varchar(256),
    Brand varchar(256),
    remark varchar(600),
    Enterprise varchar(256),
    Kind char,
    Act varchar(256),
    Director varchar(256),
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    AdId int,
    ListID int not null,
    Feaname varchar(100),
    HeadId int not null,
    ischeck char,
    pcheck char,
    IsHand char,
    SampleID int,
    BeginTime varchar(50),
    HeadCheck char,
    SubmitTime datetime,
    ProId int,
    Programa varchar(100),
    PROVINCENAME varchar(50),
    IsSubmit char
)create VIEW V_PlayStream (
    SId int not null,
    FilePath varchar(256) not null,
    FileName varchar(50),
    SampleId int not null,
    ServerId int not null,
    Reallen varchar(200),
    SfileName varchar(200),
    SampleType char,
    Ip varchar(20) not null,
    IpType varchar(10) not null,
    Port int not null,
    Channelno varchar(10),
    CutDate varchar(6),
    MediaType char
)create VIEW V_Result_chongfu (
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    MediaType char,
    PlayDate datetime
)create VIEW V_Result_chongfu2 (
    ReportId int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId char,
    MediaType char,
    CheckName varchar(256),
    TypeName varchar(50),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId varchar(10),
    Act varchar(256),
    PlayDate datetime,
    IsSex char,
    IllegalItem char(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    RulesLevel char,
    InsertTime datetime,
    ImagePath varchar(256),
    MoveBusiness varchar(10),
    AnnouncementID varchar(10)
)create VIEW V_SamCheck (
    SampleID int not null,
    ChannelNo varchar(9),
    SampleFile varchar(256),
    FeatureFile varchar(256),
    SamDate varchar(10),
    SamBPos varchar(50),
    SamEPos varchar(50),
    SampleLen varchar(50),
    CreateTime varchar(50),
    FileName varchar(50),
    LastTime varchar(50),
    FileId int not null,
    Feaname varchar(100),
    FilePath varchar(256),
    IsHand char,
    BDatetime varchar(20),
    IsFMove char,
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    MediaType varchar(50),
    remark varchar(256),
    Act varchar(256),
    remark2 varchar(256),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    ChannelName varchar(100),
    inserttime datetime,
    CheckTime datetime,
    EnterpriseId varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    CheckName varchar(256),
    samcheck char,
    IsChecked char
)create VIEW V_SAMListID (
    ListID int not null,
    HeadId int not null,
    SampleID int not null
)create VIEW V_Sample (
    SampleID int not null,
    ChannelNo varchar(9),
    SampleFile varchar(256),
    FeatureFile varchar(256),
    SampleLen varchar(50),
    CreateTime varchar(50),
    LastTime varchar(50),
    AdId int,
    ADName varchar(256),
    Brand varchar(256),
    Version varchar(256),
    Enterprise varchar(256),
    MediaType varchar(50),
    remark varchar(600),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    IsStop char,
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    SamDate varchar(10),
    SamBPos varchar(50),
    SamEPos varchar(50),
    FileName varchar(50),
    EnterpriseId varchar(256),
    CheckName varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    SampleIsstop char
)create VIEW V_samplepath (
    SId int,
    FilePath varchar(256),
    FileName varchar(50),
    SampleId int,
    ServerId int,
    Reallen varchar(200),
    SfileName varchar(200),
    SampleType char,
    InsertTime datetime,
    Channelno varchar(10),
    cutdate varchar(6),
    MediaType char
)create VIEW V_SampleUpload (
    Feaname varchar(100),
    FilePath varchar(512),
    SampleId varchar(50),
    AdId varchar(50),
    IsHand char,
    IsChecked char,
    IsFMove char,
    Channelno varchar(10),
    CutDate varchar(6),
    iscut char,
    IsCheck char,
    isupload char,
    Expr1 varchar(256) not null
)create VIEW V_StationInfo (
    ChannelNo varchar(20),
    ChannelName varchar(100),
    MediaType char
)create VIEW V_tempAdinfo (
    AdId int not null,
    ADName varchar(256),
    Version varchar(256),
    Brand varchar(256),
    Enterprise varchar(256),
    MediaType varchar(50),
    remark varchar(600),
    Act varchar(256),
    Director varchar(256),
    Kind char,
    Tag char,
    inserttime datetime,
    IsStop char,
    EnterpriseId varchar(256),
    remark2 varchar(600),
    IsSex char,
    RunEnterprise varchar(256),
    FactureEnterprise varchar(600),
    ProductApprovalNo varchar(600),
    ADApprovalNo varchar(600),
    CheckADApprovalNo varchar(256),
    themeid int,
    TypeName varchar(50) not null,
    TypeId varchar(50) not null
)create VIEW V_Typeid (
    typeid int,
    themeid int,
    IllegalNature char,
    adid int,
    TypeName varchar(50) not null,
    IsChecked char
)create VIEW V_wgxiang (
    OutlawCord varchar(20),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    ThemeId int not null,
    ThemeName varchar(10) not null,
    TypeId varchar(50) not null,
    TypeName varchar(50) not null,
    OutlawId int not null
)create VIEW V_yingshiju (
    AREANAME varchar(100),
    PROVINCENAME varchar(50),
    CITYNAME varchar(50),
    COUNTYNAME varchar(50),
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(100),
    TypeName varchar(50),
    AdId int,
    ADName varchar(256),
    Version varchar(256),
    PlayDate varchar(10),
    BTime varchar(14),
    ETime varchar(14),
    HeadId int
)create VIEW VIEW2 (
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    TypeId varchar(5),
    MediaType char,
    CheckName varchar(256),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    PlayDate datetime,
    AdId int,
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char
)create VIEW VIEW3 (
    adid int,
    typeid int,
    IllegalNature char,
    TypeName varchar(50) not null,
    ThemeName varchar(10) not null,
    OutlawCord varchar(20),
    OutlawId int not null,
    OutlawName varchar(500),
    OutlawNorm varchar(500),
    OutlawLevel varchar(50),
    ThemeId int not null
)create VIEW VIEW4 (
    Reportid int not null,
    Channelno varchar(10),
    AdName varchar(256),
    BeginTime varchar(10),
    EndTime varchar(10),
    ThemeId int,
    TypeId varchar(5),
    MediaType char,
    CheckName varchar(256),
    TypeName varchar(50),
    RunEnterprise varchar(256),
    FactureEnterprise varchar(256),
    ProductApprovalNo varchar(256),
    ADApprovalNo varchar(256),
    CheckApprovalNo varchar(256),
    CheckEnterprise varchar(256),
    EnterpriseArea varchar(256),
    EnterpriseId varchar(10),
    Act varchar(256),
    PlayDate datetime,
    IsSex char,
    IllegalItem varchar(50),
    AdId int,
    ChannelName varchar(256),
    PlayLean varchar(50),
    SampleId varchar(10),
    SampleType char,
    RulesLevel char,
    InsertTime datetime,
    ImagePath varchar(256),
    MoveBusiness varchar(10),
    AnnouncementID varchar(10),
    headId int,
    plid int,
    ischeck char
)create VIEW VIEW5 (
    typeid varchar(50),
    IllegalNature char,
    TypeName varchar(50) not null,
    ChannelNo varchar(9),
    MediaType char,
    ChannelName varchar(100),
    PlayDate varchar(10),
    StartPos varchar(95),
    EndPos varchar(95),
    ADName varchar(256),
    playlean int,
    Enterprise varchar(256),
    AdId int,
    themeid int
)
create PROCEDURE dt_addtosourcecontrol(@vchSourceSafeINI varchar, @vchProjectName varchar, @vchComment varchar, @vchLoginName varchar, @vchPassword varchar);
create PROCEDURE dt_addtosourcecontrol_u(@vchSourceSafeINI sysname, @vchProjectName sysname, @vchComment sysname, @vchLoginName sysname, @vchPassword sysname);
create PROCEDURE dt_adduserobject();
create PROCEDURE dt_adduserobject_vcs(@vchProperty varchar);
create PROCEDURE dt_checkinobject(@chObjectType char, @vchObjectName varchar, @vchComment varchar, @vchLoginName varchar, @vchPassword varchar, @iVCSFlags int, @iActionFlag int, @txStream1 text, @txStream2 text, @txStream3 text);
create PROCEDURE dt_checkinobject_u(@chObjectType char, @vchObjectName sysname, @vchComment sysname, @vchLoginName sysname, @vchPassword sysname, @iVCSFlags int, @iActionFlag int, @txStream1 text, @txStream2 text, @txStream3 text);
create PROCEDURE dt_checkoutobject(@chObjectType char, @vchObjectName varchar, @vchComment varchar, @vchLoginName varchar, @vchPassword varchar, @iVCSFlags int, @iActionFlag int);
create PROCEDURE dt_checkoutobject_u(@chObjectType char, @vchObjectName sysname, @vchComment sysname, @vchLoginName sysname, @vchPassword sysname, @iVCSFlags int, @iActionFlag int);
create PROCEDURE dt_displayoaerror(@iObject int, @iresult int);
create PROCEDURE dt_displayoaerror_u(@iObject int, @iresult int);
create PROCEDURE dt_droppropertiesbyid(@id int, @property varchar);
create PROCEDURE dt_dropuserobjectbyid(@id int);
create PROCEDURE dt_generateansiname(@name varchar);
create PROCEDURE dt_getobjwithprop(@property varchar, @value varchar);
create PROCEDURE dt_getobjwithprop_u(@property varchar, @uvalue sysname);
create PROCEDURE dt_getpropertiesbyid(@id int, @property varchar);
create PROCEDURE dt_getpropertiesbyid_u(@id int, @property varchar);
create PROCEDURE dt_getpropertiesbyid_vcs(@id int, @property varchar, @value varchar);
create PROCEDURE dt_getpropertiesbyid_vcs_u(@id int, @property varchar, @value sysname);
create PROCEDURE dt_isundersourcecontrol(@vchLoginName varchar, @vchPassword varchar, @iWhoToo int);
create PROCEDURE dt_isundersourcecontrol_u(@vchLoginName sysname, @vchPassword sysname, @iWhoToo int);
create PROCEDURE dt_removefromsourcecontrol();
create PROCEDURE dt_setpropertybyid(@id int, @property varchar, @value varchar, @lvalue image);
create PROCEDURE dt_setpropertybyid_u(@id int, @property varchar, @uvalue sysname, @lvalue image);
create PROCEDURE dt_validateloginparams(@vchLoginName varchar, @vchPassword varchar);
create PROCEDURE dt_validateloginparams_u(@vchLoginName sysname, @vchPassword sysname);
create PROCEDURE dt_vcsenabled();
create PROCEDURE dt_verstamp006();
create PROCEDURE dt_verstamp007();
create PROCEDURE dt_whocheckedout(@chObjectType char, @vchObjectName varchar, @vchLoginName varchar, @vchPassword varchar);
create PROCEDURE dt_whocheckedout_u(@chObjectType char, @vchObjectName sysname, @vchLoginName sysname, @vchPassword sysname);
create FUNCTION fn_diagramobjects();
create PROCEDURE sp_alterdiagram(@diagramname sysname, @owner_id int, @version int, @definition varbinary);
create PROCEDURE sp_creatediagram(@diagramname sysname, @owner_id int, @version int, @definition varbinary);
create PROCEDURE sp_dropdiagram(@diagramname sysname, @owner_id int);
create PROCEDURE sp_helpdiagramdefinition(@diagramname sysname, @owner_id int);
create PROCEDURE sp_helpdiagrams(@diagramname sysname, @owner_id int);
create PROCEDURE sp_renamediagram(@diagramname sysname, @owner_id int, @new_diagramname sysname);