/*
Navicat SQL Server Data Transfer

Source Server         : 192.168.0.7
Source Server Version : 105000
Source Host           : 192.168.0.7:1433
Source Database       : CTCJBSample151124
Source Schema         : dbo

Target Server Type    : SQL Server
Target Server Version : 105000
File Encoding         : 65001

Date: 2015-12-19 15:08:45
*/


-- ----------------------------
-- Table structure for T_JBUser
-- ----------------------------
DROP TABLE [dbo].[T_JBUser]
CREATE TABLE [dbo].[T_JBUser] (
[id] int NOT NULL IDENTITY(1,1) ,
[userid] varchar(50) NULL ,
[username] varchar(50) NULL ,
[password] varchar(50) NULL ,
[UserArea] varchar(500) NULL DEFAULT '' ,
[isuse] char(1) NULL DEFAULT ((0)) ,
[userType] char(1) NULL DEFAULT ((0)) ,
[Backup] char(1) NULL ,
[DataUpload] char(1) NULL DEFAULT ((0)) ,
[UserRole] varchar(255) NOT NULL DEFAULT '' 
)


DBCC CHECKIDENT(N'[dbo].[T_JBUser]', RESEED, 513)

-- ----------------------------
-- Records of T_JBUser
-- ----------------------------
SET IDENTITY_INSERT [dbo].[T_JBUser] ON
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'3', N'admin', N'admin', N'bushuo1', N'', N'0', N'3', N'3', N'1', N'数据处理员')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'4', N'linmonan', N'linmonan', N'123456', N'', N'0', N'0', N'0', N'0', N'数据复核员')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'5', N'wangzheng', N'wangzheng', N'123456', N'', N'0', N'0', N'0', N'0', N'数据质检员')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'8', N'吝默楠', N'吝默楠', N'lmn8293', N'''河北省',''山西省',''陕西省',''海南省',''福建省',''广东省',''浙江省',''重庆市'', N'0', N'3', N'2', N'1', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'10', N'鲍静', N'鲍静', N'13579', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'11', N'周鹏', N'周鹏', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'12', N'姚玉婷', N'姚玉婷', N'1', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'13', N'鲍洁', N'鲍洁', N'bj1346', N'0', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'14', N'李怡静', N'李怡静', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'16', N'赵兴杰', N'赵兴杰', N'zxj654321', N'''北京市',''河南省',''四川省',''黑龙江省'',''青海省',''西藏自治区',''新疆维吾尔自治区'',''广西壮族自治区'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'19', N'高丽', N'高丽', N'2463', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'20', N'唐倩', N'唐倩', N'tq666', N'''甘肃省',''贵州省',''江苏省',''辽宁省',''内蒙古自治区'',''山东省',''上海市',''云南省'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'21', N'徐荣凤', N'徐荣凤', N'xrffuwu', N'''甘肃省',''贵州省',''江苏省',''辽宁省',''内蒙古自治区'',''山东省',''上海市',''云南省'', N'0', N'3', N'2', N'1', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'22', N'张莹莹', N'张莹莹', N'zyy654321', N'''河北省',''山西省',''陕西省',''海南省',''福建省',''广东省',''浙江省',''重庆市'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'23', N'于丹', N'于丹', N'ydyd', N'''天津市',''湖南省',''湖北省',''安徽省',''吉林省',''江西省',''宁夏回族自治区'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'24', N'贾楠', N'贾楠', N'123', N'''天津市',''湖南省',''湖北省',''安徽省',''吉林省',''江西省',''宁夏回族自治区'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'25', N'王琳', N'王琳', N'123', N'''北京市',''河南省',''四川省',''黑龙江省'',''青海省',''西藏自治区',''新疆维吾尔自治区'',''广西壮族自治区'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'26', N'王肖依', N'王肖依', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'30', N'唐兰兰', N'唐兰兰', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'32', N'冀语', N'冀语', N'jy654321', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'53', N'周建瑜', N'周建瑜', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'56', N'赵娜a', N'赵娜a', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'57', N'朱风荣', N'朱风荣', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'58', N'赵梦', N'赵梦', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'60', N'崔爱月', N'崔爱月', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'63', N'田茜', N'田茜', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'67', N'张蕊', N'张蕊', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'71', N'刘晓夏', N'刘晓夏', N'369', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'72', N'test', N'测试', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'100', N'金明立', N'金明立', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'101', N'段晶晶', N'段晶晶', N'duanjingjing', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'103', N'王丽丽', N'王丽丽', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'104', N'韩文娟', N'韩文娟', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'105', N'刘菲', N'刘菲', N'lf654321', N'', N'0', N'0', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'107', N'李辛璐', N'李辛璐', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'108', N'李烨', N'李烨', N'ly654321', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'109', N'曹莉', N'曹莉', N'cl6543210', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'110', N'韩冰', N'韩冰', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'111', N'王娜', N'王娜', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'112', N'云雪', N'云雪', N'123456', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'113', N'张彦艳', N'张彦艳', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'114', N'张雪梅', N'张雪梅', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'115', N'王征', N'王征', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'116', N'高利静', N'高利静', N'gaolijing', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'117', N'刘春英', N'刘春英', N'123456', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'118', N'宋严严', N'宋严严', N'1987', N'', N'1', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'119', N'安洋', N'安洋', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'120', N'张悦', N'张悦', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'123', N'闫玉超', N'闫玉超', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'125', N'王家坤', N'王家坤', N'wjk', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'126', N'王凤', N'王凤', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'127', N'赵健', N'赵健', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'128', N'陈彩霞', N'陈彩霞', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'129', N'郭静华', N'郭静华', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'130', N'杜欣', N'杜欣', N'123456', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'131', N'吴朦', N'吴朦', N'123', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'132', N'高凤霞', N'高凤霞', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'133', N'李旭冉', N'李旭冉', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'135', N'刘丹', N'刘丹', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'136', N'张丽娜', N'张丽娜', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'137', N'张强', N'张强', N'123456', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'138', N'杨平', N'杨平', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'139', N'贾淑华', N'贾淑华', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'140', N'李然', N'李然', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'141', N'杨纪辉', N'杨纪辉', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'142', N'韩婷婷', N'韩婷婷', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'143', N'贾凯苗', N'贾凯苗', N'123456', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'145', N'陈婷婷', N'陈婷婷', N'123456', N'0', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'146', N'冯超', N'冯超', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'147', N'王文倩', N'王文倩', N'wwq519', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'148', N'郭静', N'郭静', N'gj654321', N'0', N'1', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'149', N'何姗姗', N'何姗姗', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'150', N'王春妹', N'王春妹', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'151', N'王颖', N'王颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'152', N'冀语', N'冀语', N'jy654321', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'153', N'张企', N'张企', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'154', N'鲍贺丽', N'鲍贺丽', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'155', N'冯思佳', N'冯思佳', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'156', N'高飞飞', N'高飞飞', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'157', N'贾梦莹', N'贾梦莹', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'158', N'姜云飞', N'姜云飞', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'159', N'李茜', N'李茜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'160', N'李铁铮', N'李铁铮', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'161', N'李云', N'李云', N'0.', N'0', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'162', N'李中会', N'李中会', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'163', N'刘顺宇', N'刘顺宇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'164', N'刘晓漫', N'刘晓漫', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'165', N'马静', N'马静', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'166', N'蒙宏亮', N'蒙宏亮', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'167', N'牛亚东', N'牛亚东', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'168', N'潘静宇', N'潘静宇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'169', N'潘星宇', N'潘星宇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'170', N'潘云霞', N'潘云霞', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'171', N'秦晓春', N'秦晓春', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'172', N'孙雅梅', N'孙雅梅', N'sun45', N'0', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'173', N'王丽华', N'王丽华', N'123456', N'0', N'0', N'0', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'174', N'王英娜', N'王英娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'175', N'魏亚男', N'魏亚男', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'176', N'吴鹏飞', N'吴鹏飞', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'177', N'邢建杰', N'邢建杰', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'178', N'于冬梅', N'于冬梅', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'179', N'张瑶', N'张瑶', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'180', N'赵军', N'赵军', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'181', N'赵美宇', N'赵美宇', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'182', N'赵爽', N'赵爽', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'183', N'周凡', N'周凡', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'184', N'毕娜', N'毕娜', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'185', N'陈超', N'陈超', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'186', N'陈晨', N'陈晨', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'187', N'陈小庆', N'陈小庆', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'188', N'戴亚铭', N'戴亚铭', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'189', N'邸智萍', N'邸智萍', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'190', N'董飞雪', N'董飞雪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'191', N'杜明静', N'杜明静', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'192', N'付强', N'付强', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'193', N'高飏', N'高飏', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'194', N'龚园园', N'龚园园', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'195', N'郝婷', N'郝婷', N'3362829ht', N'0', N'0', N'2', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'196', N'黄立云', N'黄立云', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'197', N'李剑', N'李剑', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'198', N'李丽', N'李丽', N'123456', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'199', N'李娜', N'李娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'200', N'李鹏越', N'李鹏越', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'201', N'李欣', N'李欣', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'202', N'刘丽丽', N'刘丽丽', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'203', N'刘丽平', N'刘丽平', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'204', N'刘璐', N'刘璐', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'205', N'刘瑞', N'刘瑞', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'206', N'刘文月', N'刘文月', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'207', N'刘雪莉', N'刘雪莉', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'208', N'刘亚欣', N'刘亚欣', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'209', N'刘映雪', N'刘映雪', N'1', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'210', N'吕劲', N'吕劲', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'211', N'罗丹', N'罗丹', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'212', N'么远', N'么远', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'213', N'苗珊珊', N'苗珊珊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'214', N'乔颖', N'乔颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'215', N'茹丽娜', N'茹丽娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'216', N'史立娜', N'史立娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'217', N'宋然然', N'宋然然', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'218', N'王欢', N'王欢', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'219', N'王敬', N'王敬', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'220', N'王黎燕', N'王黎燕', N'123456', N'0', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'221', N'王倩', N'王倩', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'222', N'王晓', N'王晓', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'223', N'王兴', N'王兴', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'224', N'王悦华', N'王悦华', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'225', N'吴利杰', N'吴利杰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'226', N'吴梦娇', N'吴梦娇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'227', N'吴扬', N'吴扬', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'228', N'邢丹', N'邢丹', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'229', N'邢雅莲', N'邢雅莲', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'230', N'许培培', N'许培培', N'123', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'231', N'许颖', N'许颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'232', N'闫妍', N'闫妍', N'584520', N'0', N'0', N'0', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'233', N'杨慧', N'杨慧', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'234', N'杨洁', N'杨洁', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'235', N'杨巍', N'杨巍', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'236', N'杨运辉', N'杨运辉', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'237', N'于春', N'于春', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'238', N'于盛楠', N'于盛楠', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'239', N'袁志佳', N'袁志佳', N'123456', N'0', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'240', N'苑颖', N'苑颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'241', N'张丹', N'张丹', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'242', N'张骏', N'张骏', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'243', N'张磊', N'张磊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'244', N'张娜', N'张娜', N'1', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'245', N'张晓敏', N'张晓敏', N'123456', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'246', N'张鑫', N'张鑫', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'247', N'张钰昕', N'张钰昕', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'248', N'赵义芳', N'赵义芳', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'249', N'赵娜', N'赵娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'250', N'郑晓峥', N'郑晓峥', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'251', N'周颖', N'周颖', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'252', N'朱娜', N'朱娜', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'253', N'朱霞', N'朱霞', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'254', N'朱云', N'朱云', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'255', N'金志强', N'金志强', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'256', N'鄂卫群', N'鄂卫群', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'257', N'池玉洁', N'池玉洁', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'258', N'蔺晓丹', N'蔺晓丹', N'1', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'259', N'侯盼盼', N'侯盼盼', N'123456', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'260', N'王宏海', N'王宏海', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'261', N'朱磊', N'朱磊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'262', N'刘昊昱', N'刘昊昱', N'123456', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'263', N'冯平', N'冯平', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'264', N'张悦远', N'张悦远', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'265', N'孙耀光', N'孙耀光', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'266', N'吴静宇', N'吴静宇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'267', N'琚亚涛', N'琚亚涛', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'268', N'李善武', N'李善武', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'269', N'史凤军', N'史凤军', N'1', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'270', N'杜雪颖', N'杜雪颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'271', N'安媛', N'安媛', N'123456', N'0', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'272', N'孙琳', N'孙琳', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'273', N'齐雅梦', N'齐雅梦', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'274', N'孙苹戈', N'孙苹戈', N'spg654321', N'0', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'275', N'张小娟', N'张小娟', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'276', N'刘小榕', N'刘小榕', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'277', N'刘洋', N'刘洋', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'278', N'刘爱', N'刘爱', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'279', N'崔艳娜', N'崔艳娜', N'0230', N'0', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'280', N'杨柳3.24', N'杨柳3.24', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'281', N'柳旭兰', N'柳旭兰', N'1', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'282', N'陈忱', N'陈忱', N'762500', N'', N'0', N'2', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'283', N'高丹', N'高丹', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'284', N'曹琪', N'曹琪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'285', N'信海娇', N'信海娇', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'286', N'闫韵春', N'闫韵春', N'123456', N'0', N'0', N'2', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'287', N'张红艳', N'张红艳', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'288', N'郑宏娟', N'郑宏娟', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'289', N'刘新杰', N'刘新杰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'290', N'许璐', N'许璐', N'123456', N'0', N'0', N'2', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'291', N'刘蕾', N'刘蕾', N'123456', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'292', N'娄晓雪', N'娄晓雪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'293', N'郭玉红', N'郭玉红', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'294', N'曹海潮', N'曹海潮', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'295', N'朱雪飞', N'朱雪飞', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'296', N'程艳光', N'程艳光', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'297', N'赵美洁', N'赵美洁', N'1', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'298', N'付泽琳', N'付泽琳', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'299', N'柳冬雨', N'柳冬雨', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'300', N'陈辰', N'陈辰', N'123456', N'0', N'1', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'301', N'随明宏', N'随明宏', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'302', N'于志亚', N'于志亚', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'303', N'高金凤', N'高金凤', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'304', N'杨柳4.14', N'杨柳4.14', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'305', N'刘梦莹', N'刘梦莹', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'306', N'闫爽', N'闫爽', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'307', N'魏文惠', N'魏文惠', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'308', N'王雪伟', N'王雪伟', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'309', N'何丽艳', N'何丽艳', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'310', N'任丽华', N'任丽华', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'311', N'宋宇', N'宋宇', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'312', N'聂晶', N'聂晶', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'313', N'郭玲玉', N'郭玲玉', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'314', N'高方园', N'高方园', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'315', N'王雪', N'王雪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'316', N'王文静', N'王文静', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'317', N'周璇', N'周璇', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'318', N'刘丹丹', N'刘丹丹', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'319', N'陆惠娟', N'陆惠娟', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'320', N'杜彦霖', N'杜彦霖', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'321', N'罗达', N'罗达', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'322', N'李杰', N'李杰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'323', N'刘杨', N'刘杨', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'324', N'郭传军', N'郭传军', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'325', N'闫光蕊', N'闫光蕊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'326', N'张旭', N'张旭', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'327', N'高杰', N'高杰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'328', N'殷美玲', N'殷美玲', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'329', N'刘欣', N'刘欣', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'330', N'党亚楠', N'党亚楠', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'331', N'宋健', N'宋健', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'332', N'包小兰', N'包小兰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'336', N'zzz', N'zzz', N'123456', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'339', N'崔军', N'崔军', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'340', N'孙丹5.12', N'孙丹5.12', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'341', N'杨柳', N'杨柳', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'342', N'高金凤1', N'高金凤1', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'343', N'王雪伟1', N'王雪伟1', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'344', N'闫爽1', N'闫爽1', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'345', N'史凤军1', N'史凤军1', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'346', N'徐晓晨5.26', N'徐晓晨5.26', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'347', N'赵宇坤5.27', N'赵宇坤5.27', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'348', N'肖跃兴5.26', N'肖跃兴5.26', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'349', N'吴成成5.26', N'吴成成5.26', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'350', N'张芳', N'张芳', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'351', N'钱超', N'钱超', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'352', N'张家林5.12', N'张家林5.12', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'353', N'刘秀林6.3', N'刘秀林6.3', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'354', N'毕丽娜6.9', N'毕丽娜6.9', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'355', N'姜曼6.9', N'姜曼6.9', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'356', N'李小娇6.9', N'李小娇6.9', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'357', N'刘春宇6.9', N'刘春宇6.9', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'358', N'李伟6.16', N'李伟6.16', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'359', N'刘润新6.6', N'刘润新6.6', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'360', N'程英飒6.16', N'程英飒6.16', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'361', N'王婷婷', N'王婷婷', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'362', N'马烨', N'马烨', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'363', N'刘妍', N'刘妍', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'364', N'党亚男', N'党亚男', N'123456', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'365', N'王丽婷', N'王丽婷', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'366', N'魏娜', N'魏娜', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'367', N'王烨6.25', N'王烨6.25', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'368', N'王钰英6.25', N'王钰英6.25', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'369', N'郭雅仙', N'郭雅仙', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'370', N'王钰莹6.25', N'王钰莹6.25', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'371', N'张博程6.30', N'张博程6.30', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'372', N'刘冬璐6.30', N'刘冬璐6.30', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'373', N'李晨露', N'李晨露', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'374', N'郭金迪6.30', N'郭金迪6.30', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'375', N'赵静6.30', N'赵静6.30', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'376', N'王巍6.30', N'王巍6.30', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'377', N'刘晓漫1', N'刘晓漫1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'378', N'鲍贺丽1', N'鲍贺丽1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'379', N'张晓敏1', N'张晓敏1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'380', N'吴扬1', N'吴扬1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'381', N'王颖1', N'王颖1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'382', N'王欢1', N'王欢1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'383', N'么远1', N'么远1', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'384', N'王丽华1', N'王丽华1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'385', N'柳佳微', N'柳佳微', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'386', N'安洋+', N'安洋+', N'ay123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'387', N'张鑫+', N'张鑫+', N'zx123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'388', N'刘洋1', N'刘洋1', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'389', N'王倩+', N'王倩+', N'123456', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'390', N'宋朋朋', N'宋朋朋', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'391', N'戴亚铭1', N'戴亚铭1', N'123456', N'', N'0', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'392', N'孙红梅7.21', N'孙红梅7.21', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'393', N'张玉改7.21', N'张玉改7.21', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'394', N'赵晓芳7.21', N'赵晓芳7.21', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'395', N'刘日7.21', N'刘日7.21', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'396', N'邢阳7.21', N'邢阳7.21', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'397', N'程艺7.21', N'程艺7.21', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'398', N'徐力力7.21', N'徐力力7.21', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'399', N'杨洋7.21', N'杨洋7.21', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'400', N'张艳秋7.21', N'张艳秋7.21', N'hmq123', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'401', N'乔羽714', N'乔羽714', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'402', N'张东伟7.21', N'张东伟7.21', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'403', N'许璐+', N'许璐+', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'404', N'王丽婷7.22', N'王丽婷7.22', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'405', N'朱翊萌7.28', N'朱翊萌7.28', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'406', N'张雨薇7.28', N'张雨薇7.28', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'407', N'范晶晶7.29', N'范晶晶7.29', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'408', N'刘霜霜7.29', N'刘霜霜7.29', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'409', N'于敏7.28', N'于敏7.28', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'410', N'白雪儿7.28', N'白雪儿7.28', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'411', N'宋然然1', N'宋然然1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'412', N'朱珊7.21', N'朱珊7.21', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'413', N'许颖+', N'许颖+', N'123456', N'', N'0', N'2', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'414', N'王丽丽+', N'王丽丽+', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'415', N'汤雅靖8.8', N'汤雅靖8.8', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'416', N'宋飞8.11', N'宋飞8.11', N'123456', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'417', N'乔颖+', N'乔颖+', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'418', N'龚媛媛', N'龚媛媛', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'419', N'张鑫1', N'张鑫1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'420', N'张鑫2', N'张鑫2', N'233576', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'421', N'张洁', N'张洁', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'422', N'王凤1', N'王凤1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'423', N'殷美玲1', N'殷美玲1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'424', N'张丽莉', N'张丽莉', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'425', N'陈忱2', N'陈忱2', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'426', N'丛姗10.28', N'丛姗10.28', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'427', N'李微10.28', N'李微10.28', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'428', N'王颖10.28', N'王颖10.28', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'429', N'张颖10.28', N'张颖10.28', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'430', N'邢建杰2.24', N'邢建杰2.24', N'123', N'', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'431', N'金志强3.17', N'金志强3.17', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'432', N'张颖', N'张颖', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'433', N'陈忱1', N'陈忱1', N'762500', N'', N'1', N'2', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'434', N'王黎燕1', N'王黎燕1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'435', N'柳佳微6.30', N'柳佳微6.30', N'123456', N'', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'436', N'高玉敬12.01', N'高玉敬12.01', N'123', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'437', N'包小兰1', N'包小兰1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'438', N'张丽娜1', N'张丽娜1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'439', N'董飞雪1', N'董飞雪1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'440', N'赵兴杰1', N'赵兴杰1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'441', N'党亚男1', N'党亚男1', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'442', N'赵丹12.16', N'赵丹12.16', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'443', N'严冬琳', N'严冬琳', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'444', N'宋佳', N'宋佳', N'123456', N'', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'445', N'xcb', N'xcb', N'123456', N'', N'0', N'3', N'3', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'446', N'yaoxian', N'姚先', N'123', N'', N'0', N'2', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'447', N'田智勇', N'田智勇', N'19861102', N'', N'0', N'2', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'448', N'赵娟娟', N'赵娟娟', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'449', N'代淑烨', N'代淑烨', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'450', N'周朋', N'周朋', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'451', N'陈爱国', N'陈爱国', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'452', N'刘冰', N'刘冰', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'453', N'李伟', N'李伟', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'454', N'刘景轩', N'刘景轩', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'455', N'李涵', N'李涵', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'456', N'刘日', N'刘日', N'1', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'457', N'王巍', N'王巍', N'1', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'458', N'赵茜', N'赵茜', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'459', N'陈茜', N'陈茜', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'460', N'沈微', N'沈微', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'461', N'谢朋桐', N'谢朋桐', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'462', N'代育蕊', N'代育蕊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'463', N'张亚男', N'张亚男', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'464', N'刘珊', N'刘珊', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'465', N'闫韵春1', N'闫韵春1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'466', N'周轶', N'周轶', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'467', N'赵美芳', N'赵美芳', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'468', N'张振涛', N'张振涛', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'469', N'赵航', N'赵航', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'470', N'邢芮雪', N'邢芮雪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'471', N'范迎雪', N'范迎雪', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'472', N'袁志佳1', N'袁志佳1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'473', N'朱琳1-133', N'朱琳1-133', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'474', N'王珊珊1-134', N'王珊珊1-134', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'475', N'王明媚1-88', N'王明媚1-88', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'476', N'刘菲1-92', N'刘菲1-92', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'477', N'魏伟1-82', N'魏伟1-82', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'478', N'白文洁1-147', N'白文洁1-147', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'479', N'王慧1-148', N'王慧1-148', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'480', N'朱琳', N'朱琳', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'481', N'刘菲1', N'刘菲1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'482', N'范迎雪1', N'范迎雪1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'483', N'邢丹1', N'邢丹1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'484', N'范迎雪11', N'范迎雪11', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'485', N'朱琳1', N'朱琳1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'486', N'刘菲11', N'刘菲11', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'487', N'程艺', N'程艺', N'123', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'488', N'孙颖', N'孙颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'489', N'付婷婷', N'付婷婷', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'490', N'张艳玲', N'张艳玲', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'491', N'张兰', N'张兰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'492', N'张萌', N'张萌', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'493', N'马军', N'马军', N'123456', N'0', N'1', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'494', N'张兰1', N'张兰1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'495', N'赵丹1', N'赵丹1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'496', N'冯思佳1', N'冯思佳1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'497', N'张萌1', N'张萌1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'498', N'付婷婷1', N'付婷婷1', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'499', N'高丽', N'高丽', N'2463', N'0', N'0', N'0', N'2', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'500', N'林森', null, null, N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'502', N'林森', N'林森', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'504', N'石洋', N'石洋', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'505', N'刘天颖', N'刘天颖', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'506', N'张靖瑶', N'张靖瑶', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'507', N'田波', N'田波', N'123', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'508', N'唐浚杰', N'唐浚杰', N'123456', N'0', N'0', N'0', N'0', N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'509', N'张艳秋', N'张艳秋', N'hmq123', N'', N'0', N'2', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'510', N'朱丽华', N'朱丽华', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'511', N'康颖', N'康颖', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'512', N'魏爽', N'魏爽', N'123456', N'', N'0', N'0', null, N'0', N'')
INSERT INTO [dbo].[T_JBUser] ([id], [userid], [username], [password], [UserArea], [isuse], [userType], [Backup], [DataUpload], [UserRole]) VALUES (N'513', N'张宇', N'张宇', N'zy123', N'', N'0', N'0', null, N'0', N'')
SET IDENTITY_INSERT [dbo].[T_JBUser] OFF

-- ----------------------------
-- Indexes structure for table T_JBUser
-- ----------------------------

-- ----------------------------
-- Primary Key structure for table T_JBUser
-- ----------------------------
ALTER TABLE [dbo].[T_JBUser] ADD PRIMARY KEY ([id]) WITH (FILLFACTOR=90)
